import type { Locale } from "./i18n";

export type LifeStepCopy = {
  journey: {
    study: string; work: string; family: string; studyBody: string; workBody: string; familyBody: string;
    title: string; currentPosition: string; words: string; sentences: string; complete: string; recognized: string;
    mapLabel: string; youAreHere: string; footerFirst: string; footerSecond: string; chooseEyebrow: string; chooseTitle: string;
    chooseBody: string; reloadTitle: string; switchTitle: string; reloadBody: string; confirmReload: string; confirmSwitch: string;
    lifeStage: string; stageOverview: string; scenariosComplete: string; scenarios: string; realLifeScenario: string;
  };
  practice: {
    wordTitle: string; wordEyebrow: string; wordHeading: string; wordsPractised: string; shuffled: string; inOrder: string;
    reloadList: string; word: string; phrase: string; listen: string; notKnown: string; skip: string; known: string;
    noWords: string; noPhrases: string; reloadWordTitle: string; reloadSentenceTitle: string; reloadBody: string; confirmReload: string;
  };
  scenario: {
    knowledge: string; vocabulary: string; conversation: string; review: string; sections: string; previous: string; next: string;
    complete: string; youDidIt: string; completionBody: string; continueNext: string; chooseNext: string; returnJourney: string;
    knowledgeEyebrow: string; knowledgeHeading: string; tipTitle: string; tipBody: string; vocabularyEyebrow: string; vocabularyHeading: string;
    vocabularyPrompt: string; conversationEyebrow: string; conversationHeading: string; fullDialogue: string; practiceMode: string;
    conversationPartner: string; tapToListen: string; realLifePractice: string; line: string; playLine: string; whatPractised: string;
    reviewPrompt: string; takeaway: string;
  };
  common: { back: string; close: string; clear: string; install: string; practiceMenu: string; wordPractice: string; sentencePractice: string; splashTagline: string };
};

type LifeStepExtras = {
  journey: { scenario: string; changePath: string; choosePath: string; startJourney: string; resumeJourney: string };
  practice: {
    offlinePractice: string; sentenceTitle: string; sentenceEyebrow: string; sentenceHeading: string;
    phrasesPractised: string; wordProgress: string; phraseProgress: string;
  };
  scenario: { nextScenario: string; you: string };
  common: { appUtilities: string };
};

export type ResolvedLifeStepCopy = LifeStepCopy & {
  journey: LifeStepCopy["journey"] & LifeStepExtras["journey"];
  practice: LifeStepCopy["practice"] & LifeStepExtras["practice"];
  scenario: LifeStepCopy["scenario"] & LifeStepExtras["scenario"];
  common: LifeStepCopy["common"] & LifeStepExtras["common"];
};

const en: LifeStepCopy = {
  journey: { study: "Study", work: "Work", family: "Family", studyBody: "Build confidence for campus and everyday life.", workBody: "Settle in, find work, and grow your career.", familyBody: "Create a confident new life for your family.", title: "Journey", currentPosition: "Current position", words: "Words", sentences: "Sentences", complete: "complete", recognized: "recognized", mapLabel: "Life stages map", youAreHere: "You are here", footerFirst: "Your new life,", footerSecond: "one step closer.", chooseEyebrow: "Let’s make this yours", chooseTitle: "What brings you to Canada?", chooseBody: "Choose the path that fits you best. You can change it later.", reloadTitle: "Reload journey data?", switchTitle: "Switch to {{journey}}?", reloadBody: "The selected journey data will be loaded again, and its local progress will be cleared.", confirmReload: "Confirm reload", confirmSwitch: "Confirm switch", lifeStage: "Life stage", stageOverview: "Stage overview", scenariosComplete: "scenarios complete", scenarios: "Scenarios", realLifeScenario: "Real-life scenario" },
  practice: { wordTitle: "Word practice", wordEyebrow: "Build your everyday vocabulary", wordHeading: "Words for real life.", wordsPractised: "words practised", shuffled: "Shuffled", inOrder: "In order", reloadList: "Reload list", word: "Word", phrase: "Phrase", listen: "Listen", notKnown: "Don’t know", skip: "Skip", known: "Know", noWords: "No vocabulary is available yet. Connect once to download the practice list.", noPhrases: "No sentence phrases are available yet. Connect once to download the practice list.", reloadWordTitle: "Reload word list?", reloadSentenceTitle: "Reload sentence list?", reloadBody: "The latest list will replace the cached list, and your local progress will be cleared.", confirmReload: "Confirm reload" },
  scenario: { knowledge: "Knowledge", vocabulary: "Vocabulary", conversation: "Conversation", review: "Review", sections: "Scenario sections", previous: "Previous", next: "Next", complete: "Scenario complete", youDidIt: "You did it!", completionBody: "You’re ready to use this conversation in real life. Keep the momentum going.", continueNext: "Continue to next scenario", chooseNext: "Choose the next scenario", returnJourney: "Return to journey", knowledgeEyebrow: "Know before you go", knowledgeHeading: "Set yourself up for a good conversation.", tipTitle: "LifeStep tip", tipBody: "You don’t have to understand every word. Listen for the key question, then answer one idea at a time.", vocabularyEyebrow: "Words for the moment", vocabularyHeading: "Tap, listen, and make them yours.", vocabularyPrompt: "Tap a word to listen", conversationEyebrow: "Conversation practice", conversationHeading: "Make the moment feel familiar.", fullDialogue: "Full dialogue", practiceMode: "Practice mode", conversationPartner: "Conversation partner", tapToListen: "Tap a message to listen", realLifePractice: "Real-life practice · Canada", line: "Line", playLine: "Play line", whatPractised: "What you practised", reviewPrompt: "Tap each phrase when you can say it confidently.", takeaway: "Take this with you" },
  common: { back: "Back", close: "Close", clear: "Clear", install: "Install LifeStep", practiceMenu: "Practice", wordPractice: "Word practice", sentencePractice: "Sentence practice", splashTagline: "Step into real life" },
};

const translations: Partial<Record<Locale, LifeStepCopy>> = {
  "zh-Hans": {
    journey: { study: "学习", work: "工作", family: "家庭", studyBody: "建立校园和日常生活中的信心。", workBody: "适应生活、寻找工作并发展职业。", familyBody: "为家人创造自信的新生活。", title: "旅程", currentPosition: "当前位置", words: "单词", sentences: "句子", complete: "已完成", recognized: "认识", mapLabel: "人生阶段地图", youAreHere: "你在这里", footerFirst: "你的新生活，", footerSecond: "离目标更近一步。", chooseEyebrow: "选择属于你的旅程", chooseTitle: "你为什么来到加拿大？", chooseBody: "选择最适合你的方向，之后也可以更改。", reloadTitle: "重新加载旅程数据？", switchTitle: "切换到{{journey}}？", reloadBody: "将重新加载所选旅程数据，并清除本地进度。", confirmReload: "确认重新加载", confirmSwitch: "确认切换", lifeStage: "人生阶段", stageOverview: "阶段概览", scenariosComplete: "个场景已完成", scenarios: "场景", realLifeScenario: "真实生活场景" },
    practice: { wordTitle: "单词练习", wordEyebrow: "积累日常词汇", wordHeading: "为真实生活学习单词。", wordsPractised: "个单词已练习", shuffled: "已打乱", inOrder: "按顺序", reloadList: "重新加载列表", word: "单词", phrase: "句子", listen: "听一听", notKnown: "不认识", skip: "跳过", known: "认识", noWords: "暂时没有可用单词。联网一次即可下载练习列表。", noPhrases: "暂时没有可用句子。联网一次即可下载练习列表。", reloadWordTitle: "重新加载单词列表？", reloadSentenceTitle: "重新加载句子列表？", reloadBody: "最新列表将替换本地缓存，并清除本地练习进度。", confirmReload: "确认重新加载" },
    scenario: { knowledge: "背景知识", vocabulary: "词汇", conversation: "对话", review: "复习", sections: "场景部分", previous: "上一步", next: "下一步", complete: "场景完成", youDidIt: "做得很好！", completionBody: "你已经可以把这段对话用在真实生活中了。继续保持！", continueNext: "继续下一个场景", chooseNext: "选择下一个场景", returnJourney: "返回旅程", knowledgeEyebrow: "提前了解", knowledgeHeading: "为顺畅交流做好准备。", tipTitle: "LifeStep 提示", tipBody: "不必理解每一个单词。先听懂关键问题，再一次回答一个重点。", vocabularyEyebrow: "实用词汇", vocabularyHeading: "点击、聆听，把它们变成自己的表达。", vocabularyPrompt: "点击词汇听发音", conversationEyebrow: "对话练习", conversationHeading: "让真实交流变得熟悉。", fullDialogue: "完整对话", practiceMode: "练习模式", conversationPartner: "对话伙伴", tapToListen: "点击消息聆听", realLifePractice: "真实生活练习 · 加拿大", line: "第", playLine: "播放本句", whatPractised: "本次练习内容", reviewPrompt: "当你能自信说出每个句子时，请点击确认。", takeaway: "带走这句话" },
    common: { back: "返回", close: "关闭", clear: "清除", install: "安装 LifeStep", practiceMenu: "练习", wordPractice: "单词练习", sentencePractice: "句子练习", splashTagline: "走进真实生活" },
  },
  "zh-Hant": {
    journey: { study: "學習", work: "工作", family: "家庭", studyBody: "建立校園和日常生活中的信心。", workBody: "適應生活、尋找工作並發展職涯。", familyBody: "為家人創造自信的新生活。", title: "旅程", currentPosition: "目前位置", words: "單字", sentences: "句子", complete: "已完成", recognized: "認識", mapLabel: "人生階段地圖", youAreHere: "你在這裡", footerFirst: "你的新生活，", footerSecond: "離目標更近一步。", chooseEyebrow: "選擇屬於你的旅程", chooseTitle: "你為什麼來到加拿大？", chooseBody: "選擇最適合你的方向，之後也可以更改。", reloadTitle: "重新載入旅程資料？", switchTitle: "切換到{{journey}}？", reloadBody: "將重新載入所選旅程資料，並清除本機進度。", confirmReload: "確認重新載入", confirmSwitch: "確認切換", lifeStage: "人生階段", stageOverview: "階段概覽", scenariosComplete: "個場景已完成", scenarios: "場景", realLifeScenario: "真實生活場景" },
    practice: { wordTitle: "單字練習", wordEyebrow: "累積日常詞彙", wordHeading: "為真實生活學習單字。", wordsPractised: "個單字已練習", shuffled: "已打亂", inOrder: "依序排列", reloadList: "重新載入清單", word: "單字", phrase: "句子", listen: "聽一聽", notKnown: "不認識", skip: "跳過", known: "認識", noWords: "暫時沒有可用單字。連線一次即可下載練習清單。", noPhrases: "暫時沒有可用句子。連線一次即可下載練習清單。", reloadWordTitle: "重新載入單字清單？", reloadSentenceTitle: "重新載入句子清單？", reloadBody: "最新清單將取代本機快取，並清除本機練習進度。", confirmReload: "確認重新載入" },
    scenario: { knowledge: "背景知識", vocabulary: "詞彙", conversation: "對話", review: "複習", sections: "場景部分", previous: "上一步", next: "下一步", complete: "場景完成", youDidIt: "做得很好！", completionBody: "你已經可以把這段對話用在真實生活中了。繼續保持！", continueNext: "繼續下一個場景", chooseNext: "選擇下一個場景", returnJourney: "返回旅程", knowledgeEyebrow: "事前了解", knowledgeHeading: "為順暢交流做好準備。", tipTitle: "LifeStep 提示", tipBody: "不必理解每一個單字。先聽懂關鍵問題，再一次回答一個重點。", vocabularyEyebrow: "實用詞彙", vocabularyHeading: "點擊、聆聽，把它們變成自己的表達。", vocabularyPrompt: "點擊詞彙聽發音", conversationEyebrow: "對話練習", conversationHeading: "讓真實交流變得熟悉。", fullDialogue: "完整對話", practiceMode: "練習模式", conversationPartner: "對話夥伴", tapToListen: "點擊訊息聆聽", realLifePractice: "真實生活練習 · 加拿大", line: "第", playLine: "播放本句", whatPractised: "本次練習內容", reviewPrompt: "當你能自信說出每個句子時，請點擊確認。", takeaway: "帶走這句話" },
    common: { back: "返回", close: "關閉", clear: "清除", install: "安裝 LifeStep", practiceMenu: "練習", wordPractice: "單字練習", sentencePractice: "句子練習", splashTagline: "走進真實生活" },
  },
  fr: {
    journey: { study: "Études", work: "Travail", family: "Famille", studyBody: "Gagnez en confiance pour les études et la vie quotidienne.", workBody: "Installez-vous, trouvez un emploi et développez votre carrière.", familyBody: "Construisez une nouvelle vie de confiance pour votre famille.", title: "Parcours", currentPosition: "Position actuelle", words: "Mots", sentences: "Phrases", complete: "terminés", recognized: "connus", mapLabel: "Carte des étapes de vie", youAreHere: "Vous êtes ici", footerFirst: "Votre nouvelle vie,", footerSecond: "un pas de plus.", chooseEyebrow: "Construisons votre parcours", chooseTitle: "Qu’est-ce qui vous amène au Canada ?", chooseBody: "Choisissez le parcours qui vous convient. Vous pourrez le modifier plus tard.", reloadTitle: "Recharger les données du parcours ?", switchTitle: "Passer à {{journey}} ?", reloadBody: "Les données du parcours seront rechargées et votre progression locale sera effacée.", confirmReload: "Confirmer le rechargement", confirmSwitch: "Confirmer le changement", lifeStage: "Étape de vie", stageOverview: "Aperçu de l’étape", scenariosComplete: "scénarios terminés", scenarios: "Scénarios", realLifeScenario: "Scénario de la vie réelle" },
    practice: { wordTitle: "Exercices de vocabulaire", wordEyebrow: "Développez votre vocabulaire quotidien", wordHeading: "Des mots pour la vraie vie.", wordsPractised: "mots pratiqués", shuffled: "Mélangés", inOrder: "Dans l’ordre", reloadList: "Recharger la liste", word: "Mot", phrase: "Phrase", listen: "Écouter", notKnown: "Je ne connais pas", skip: "Passer", known: "Je connais", noWords: "Aucun mot n’est encore disponible. Connectez-vous une fois pour télécharger la liste.", noPhrases: "Aucune phrase n’est encore disponible. Connectez-vous une fois pour télécharger la liste.", reloadWordTitle: "Recharger la liste de mots ?", reloadSentenceTitle: "Recharger la liste de phrases ?", reloadBody: "La dernière liste remplacera la liste en cache et votre progression locale sera effacée.", confirmReload: "Confirmer le rechargement" },
    scenario: { knowledge: "Contexte", vocabulary: "Vocabulaire", conversation: "Conversation", review: "Révision", sections: "Sections du scénario", previous: "Précédent", next: "Suivant", complete: "Scénario terminé", youDidIt: "Bravo !", completionBody: "Vous êtes prêt à utiliser cette conversation dans la vie réelle. Continuez sur votre lancée !", continueNext: "Continuer vers le scénario suivant", chooseNext: "Choisir le scénario suivant", returnJourney: "Retour au parcours", knowledgeEyebrow: "À savoir avant de commencer", knowledgeHeading: "Préparez-vous à une bonne conversation.", tipTitle: "Conseil LifeStep", tipBody: "Vous n’avez pas besoin de comprendre chaque mot. Écoutez la question clé, puis répondez à une idée à la fois.", vocabularyEyebrow: "Les mots du moment", vocabularyHeading: "Touchez, écoutez et appropriez-vous ces mots.", vocabularyPrompt: "Touchez un mot pour l’écouter", conversationEyebrow: "Pratique de conversation", conversationHeading: "Rendez la situation familière.", fullDialogue: "Dialogue complet", practiceMode: "Mode pratique", conversationPartner: "Partenaire de conversation", tapToListen: "Touchez un message pour l’écouter", realLifePractice: "Pratique de la vie réelle · Canada", line: "Ligne", playLine: "Lire la ligne", whatPractised: "Ce que vous avez pratiqué", reviewPrompt: "Touchez chaque phrase lorsque vous pouvez la dire avec confiance.", takeaway: "À retenir" },
    common: { back: "Retour", close: "Fermer", clear: "Effacer", install: "Installer LifeStep", practiceMenu: "Pratique", wordPractice: "Exercices de vocabulaire", sentencePractice: "Exercices de phrases", splashTagline: "Entrez dans la vraie vie" },
  },
  es: {
    journey: { study: "Estudios", work: "Trabajo", family: "Familia", studyBody: "Gana confianza para los estudios y la vida diaria.", workBody: "Adáptate, encuentra trabajo y desarrolla tu carrera.", familyBody: "Crea una nueva vida llena de confianza para tu familia.", title: "Recorrido", currentPosition: "Posición actual", words: "Palabras", sentences: "Frases", complete: "completados", recognized: "conocidas", mapLabel: "Mapa de etapas de vida", youAreHere: "Estás aquí", footerFirst: "Tu nueva vida,", footerSecond: "un paso más cerca.", chooseEyebrow: "Hagamos tu recorrido", chooseTitle: "¿Qué te trae a Canadá?", chooseBody: "Elige el recorrido que mejor se adapte a ti. Puedes cambiarlo después.", reloadTitle: "¿Recargar los datos del recorrido?", switchTitle: "¿Cambiar a {{journey}}?", reloadBody: "Los datos del recorrido se cargarán de nuevo y se borrará tu progreso local.", confirmReload: "Confirmar recarga", confirmSwitch: "Confirmar cambio", lifeStage: "Etapa de vida", stageOverview: "Resumen de la etapa", scenariosComplete: "escenarios completados", scenarios: "Escenarios", realLifeScenario: "Escenario de la vida real" },
    practice: { wordTitle: "Práctica de palabras", wordEyebrow: "Amplía tu vocabulario cotidiano", wordHeading: "Palabras para la vida real.", wordsPractised: "palabras practicadas", shuffled: "Mezcladas", inOrder: "En orden", reloadList: "Recargar lista", word: "Palabra", phrase: "Frase", listen: "Escuchar", notKnown: "No la sé", skip: "Omitir", known: "La sé", noWords: "Todavía no hay vocabulario disponible. Conéctate una vez para descargar la lista.", noPhrases: "Todavía no hay frases disponibles. Conéctate una vez para descargar la lista.", reloadWordTitle: "¿Recargar la lista de palabras?", reloadSentenceTitle: "¿Recargar la lista de frases?", reloadBody: "La lista más reciente reemplazará la guardada y se borrará tu progreso local.", confirmReload: "Confirmar recarga" },
    scenario: { knowledge: "Contexto", vocabulary: "Vocabulario", conversation: "Conversación", review: "Repaso", sections: "Secciones del escenario", previous: "Anterior", next: "Siguiente", complete: "Escenario completado", youDidIt: "¡Lo lograste!", completionBody: "Ya puedes usar esta conversación en la vida real. ¡Sigue avanzando!", continueNext: "Continuar al siguiente escenario", chooseNext: "Elegir el siguiente escenario", returnJourney: "Volver al recorrido", knowledgeEyebrow: "Antes de empezar", knowledgeHeading: "Prepárate para una buena conversación.", tipTitle: "Consejo de LifeStep", tipBody: "No tienes que entender cada palabra. Escucha la pregunta clave y responde una idea a la vez.", vocabularyEyebrow: "Palabras para este momento", vocabularyHeading: "Toca, escucha y hazlas tuyas.", vocabularyPrompt: "Toca una palabra para escucharla", conversationEyebrow: "Práctica de conversación", conversationHeading: "Haz que el momento te resulte familiar.", fullDialogue: "Diálogo completo", practiceMode: "Modo de práctica", conversationPartner: "Compañero de conversación", tapToListen: "Toca un mensaje para escucharlo", realLifePractice: "Práctica de la vida real · Canadá", line: "Línea", playLine: "Reproducir línea", whatPractised: "Lo que practicaste", reviewPrompt: "Toca cada frase cuando puedas decirla con confianza.", takeaway: "Para recordar" },
    common: { back: "Atrás", close: "Cerrar", clear: "Borrar", install: "Instalar LifeStep", practiceMenu: "Práctica", wordPractice: "Práctica de palabras", sentencePractice: "Práctica de frases", splashTagline: "Entra en la vida real" },
  },
  ja: {
    journey: { study: "学習", work: "仕事", family: "家族", studyBody: "学校生活と日常生活への自信を育てます。", workBody: "生活に慣れ、仕事を見つけ、キャリアを伸ばします。", familyBody: "家族と自信を持って新しい生活を築きます。", title: "ジャーニー", currentPosition: "現在地", words: "単語", sentences: "文", complete: "完了", recognized: "覚えた数", mapLabel: "ライフステージマップ", youAreHere: "現在地", footerFirst: "あなたの新しい生活を、", footerSecond: "一歩ずつ前へ。", chooseEyebrow: "あなたの道を選びましょう", chooseTitle: "カナダに来たきっかけは？", chooseBody: "自分に合う道を選べます。後から変更することもできます。", reloadTitle: "ジャーニーデータを再読み込みしますか？", switchTitle: "{{journey}}に切り替えますか？", reloadBody: "選択したデータを再読み込みし、端末に保存された進捗を消去します。", confirmReload: "再読み込みを確認", confirmSwitch: "切り替えを確認", lifeStage: "ライフステージ", stageOverview: "ステージ概要", scenariosComplete: "シナリオ完了", scenarios: "シナリオ", realLifeScenario: "実生活のシナリオ" },
    practice: { wordTitle: "単語練習", wordEyebrow: "日常の語彙を増やしましょう", wordHeading: "実生活で使う単語。", wordsPractised: "単語を練習済み", shuffled: "シャッフル", inOrder: "順番どおり", reloadList: "リストを再読み込み", word: "単語", phrase: "文", listen: "聞く", notKnown: "知らない", skip: "スキップ", known: "知っている", noWords: "利用できる単語がありません。オンラインで一度接続すると練習リストをダウンロードできます。", noPhrases: "利用できる文がありません。オンラインで一度接続すると練習リストをダウンロードできます。", reloadWordTitle: "単語リストを再読み込みしますか？", reloadSentenceTitle: "文のリストを再読み込みしますか？", reloadBody: "最新のリストで保存済みリストを置き換え、端末の進捗を消去します。", confirmReload: "再読み込みを確認" },
    scenario: { knowledge: "知識", vocabulary: "語彙", conversation: "会話", review: "復習", sections: "シナリオの項目", previous: "前へ", next: "次へ", complete: "シナリオ完了", youDidIt: "できました！", completionBody: "この会話を実生活で使う準備ができました。この調子で続けましょう！", continueNext: "次のシナリオへ", chooseNext: "次のシナリオを選ぶ", returnJourney: "ジャーニーに戻る", knowledgeEyebrow: "始める前に", knowledgeHeading: "会話の準備をしましょう。", tipTitle: "LifeStepのヒント", tipBody: "すべての単語を理解する必要はありません。大切な質問を聞き、一度に一つの内容で答えましょう。", vocabularyEyebrow: "今回の単語", vocabularyHeading: "タップして聞き、自分の表現にしましょう。", vocabularyPrompt: "単語をタップして聞く", conversationEyebrow: "会話練習", conversationHeading: "その場面に慣れましょう。", fullDialogue: "会話全体", practiceMode: "練習モード", conversationPartner: "会話相手", tapToListen: "メッセージをタップして聞く", realLifePractice: "実生活の練習 · カナダ", line: "行", playLine: "この行を再生", whatPractised: "練習した内容", reviewPrompt: "自信を持って言えるようになった文をタップしてください。", takeaway: "覚えておきたいこと" },
    common: { back: "戻る", close: "閉じる", clear: "クリア", install: "LifeStepをインストール", practiceMenu: "練習", wordPractice: "単語練習", sentencePractice: "文の練習", splashTagline: "実生活へ一歩" },
  },
  ko: {
    journey: { study: "학습", work: "직장", family: "가족", studyBody: "학교와 일상생활에 대한 자신감을 키워요.", workBody: "생활에 적응하고 일자리를 찾아 경력을 발전시켜요.", familyBody: "가족과 함께 자신감 있는 새 삶을 만들어가요.", title: "여정", currentPosition: "현재 위치", words: "단어", sentences: "문장", complete: "완료", recognized: "아는 수", mapLabel: "인생 단계 지도", youAreHere: "현재 위치", footerFirst: "새로운 삶을", footerSecond: "한 걸음 더 가까이.", chooseEyebrow: "나에게 맞는 길을 골라요", chooseTitle: "캐나다에 온 이유는 무엇인가요?", chooseBody: "가장 잘 맞는 길을 선택하세요. 나중에 변경할 수 있어요.", reloadTitle: "여정 데이터를 다시 불러올까요?", switchTitle: "{{journey}}로 전환할까요?", reloadBody: "선택한 데이터를 다시 불러오고 로컬 진행 상황을 삭제합니다.", confirmReload: "다시 불러오기", confirmSwitch: "전환 확인", lifeStage: "인생 단계", stageOverview: "단계 개요", scenariosComplete: "시나리오 완료", scenarios: "시나리오", realLifeScenario: "실생활 시나리오" },
    practice: { wordTitle: "단어 연습", wordEyebrow: "일상 어휘를 쌓아 보세요", wordHeading: "실생활을 위한 단어.", wordsPractised: "단어 연습 완료", shuffled: "섞기", inOrder: "순서대로", reloadList: "목록 다시 불러오기", word: "단어", phrase: "문장", listen: "듣기", notKnown: "모르겠어요", skip: "건너뛰기", known: "알아요", noWords: "아직 사용할 수 있는 단어가 없습니다. 온라인에 한 번 연결하면 연습 목록을 내려받을 수 있어요.", noPhrases: "아직 사용할 수 있는 문장이 없습니다. 온라인에 한 번 연결하면 연습 목록을 내려받을 수 있어요.", reloadWordTitle: "단어 목록을 다시 불러올까요?", reloadSentenceTitle: "문장 목록을 다시 불러올까요?", reloadBody: "최신 목록으로 저장된 목록을 바꾸고 로컬 진행 상황을 삭제합니다.", confirmReload: "다시 불러오기" },
    scenario: { knowledge: "배경 지식", vocabulary: "어휘", conversation: "대화", review: "복습", sections: "시나리오 섹션", previous: "이전", next: "다음", complete: "시나리오 완료", youDidIt: "잘했어요!", completionBody: "이제 이 대화를 실생활에서 사용할 준비가 되었어요. 계속 이어가세요!", continueNext: "다음 시나리오로 계속", chooseNext: "다음 시나리오 선택", returnJourney: "여정으로 돌아가기", knowledgeEyebrow: "시작하기 전에", knowledgeHeading: "좋은 대화를 준비해 보세요.", tipTitle: "LifeStep 팁", tipBody: "모든 단어를 이해할 필요는 없어요. 핵심 질문을 듣고 한 번에 한 가지 생각으로 답하세요.", vocabularyEyebrow: "지금 필요한 단어", vocabularyHeading: "누르고 듣고 내 표현으로 만들어 보세요.", vocabularyPrompt: "단어를 눌러 듣기", conversationEyebrow: "대화 연습", conversationHeading: "상황을 익숙하게 만들어 보세요.", fullDialogue: "전체 대화", practiceMode: "연습 모드", conversationPartner: "대화 상대", tapToListen: "메시지를 눌러 듣기", realLifePractice: "실생활 연습 · 캐나다", line: "줄", playLine: "이 줄 재생", whatPractised: "연습한 내용", reviewPrompt: "자신 있게 말할 수 있는 문장을 눌러 보세요.", takeaway: "기억할 내용" },
    common: { back: "뒤로", close: "닫기", clear: "지우기", install: "LifeStep 설치", practiceMenu: "연습", wordPractice: "단어 연습", sentencePractice: "문장 연습", splashTagline: "실생활로 한 걸음" },
  },
  ru: {
    journey: { study: "Учёба", work: "Работа", family: "Семья", studyBody: "Развивайте уверенность для учёбы и повседневной жизни.", workBody: "Осваивайтесь, находите работу и развивайте карьеру.", familyBody: "Создавайте новую уверенную жизнь для своей семьи.", title: "Путь", currentPosition: "Текущая позиция", words: "Слова", sentences: "Фразы", complete: "завершено", recognized: "изучено", mapLabel: "Карта жизненных этапов", youAreHere: "Вы здесь", footerFirst: "Ваша новая жизнь —", footerSecond: "ещё один шаг вперёд.", chooseEyebrow: "Выберите свой путь", chooseTitle: "Что привело вас в Канаду?", chooseBody: "Выберите подходящий путь. Позже его можно изменить.", reloadTitle: "Перезагрузить данные пути?", switchTitle: "Перейти к пути «{{journey}}»?", reloadBody: "Данные будут загружены заново, а локальный прогресс будет удалён.", confirmReload: "Подтвердить загрузку", confirmSwitch: "Подтвердить переход", lifeStage: "Жизненный этап", stageOverview: "Обзор этапа", scenariosComplete: "сценариев завершено", scenarios: "Сценарии", realLifeScenario: "Сценарий из реальной жизни" },
    practice: { wordTitle: "Практика слов", wordEyebrow: "Расширяйте повседневный словарный запас", wordHeading: "Слова для реальной жизни.", wordsPractised: "слов изучено", shuffled: "Перемешано", inOrder: "По порядку", reloadList: "Загрузить список заново", word: "Слово", phrase: "Фраза", listen: "Слушать", notKnown: "Не знаю", skip: "Пропустить", known: "Знаю", noWords: "Слова пока недоступны. Подключитесь к интернету один раз, чтобы скачать список.", noPhrases: "Фразы пока недоступны. Подключитесь к интернету один раз, чтобы скачать список.", reloadWordTitle: "Загрузить список слов заново?", reloadSentenceTitle: "Загрузить список фраз заново?", reloadBody: "Новый список заменит сохранённый, а локальный прогресс будет удалён.", confirmReload: "Подтвердить загрузку" },
    scenario: { knowledge: "Контекст", vocabulary: "Словарь", conversation: "Разговор", review: "Повторение", sections: "Разделы сценария", previous: "Назад", next: "Далее", complete: "Сценарий завершён", youDidIt: "У вас получилось!", completionBody: "Вы готовы использовать этот разговор в реальной жизни. Продолжайте в том же духе!", continueNext: "К следующему сценарию", chooseNext: "Выбрать следующий сценарий", returnJourney: "Вернуться к пути", knowledgeEyebrow: "Что важно знать", knowledgeHeading: "Подготовьтесь к хорошему разговору.", tipTitle: "Совет LifeStep", tipBody: "Не обязательно понимать каждое слово. Услышьте главный вопрос и отвечайте по одной мысли за раз.", vocabularyEyebrow: "Слова для этой ситуации", vocabularyHeading: "Нажимайте, слушайте и используйте их сами.", vocabularyPrompt: "Нажмите на слово, чтобы услышать его", conversationEyebrow: "Практика разговора", conversationHeading: "Сделайте ситуацию знакомой.", fullDialogue: "Весь диалог", practiceMode: "Режим практики", conversationPartner: "Собеседник", tapToListen: "Нажмите на сообщение, чтобы услышать его", realLifePractice: "Практика реальной жизни · Канада", line: "Строка", playLine: "Воспроизвести строку", whatPractised: "Что вы изучили", reviewPrompt: "Нажимайте на фразы, которые вы уже можете уверенно сказать.", takeaway: "Главное" },
    common: { back: "Назад", close: "Закрыть", clear: "Очистить", install: "Установить LifeStep", practiceMenu: "Практика", wordPractice: "Практика слов", sentencePractice: "Практика фраз", splashTagline: "Шаг навстречу реальной жизни" },
  },
  vi: {
    journey: { study: "Học tập", work: "Công việc", family: "Gia đình", studyBody: "Xây dựng sự tự tin cho trường học và cuộc sống hằng ngày.", workBody: "Ổn định cuộc sống, tìm việc và phát triển sự nghiệp.", familyBody: "Cùng gia đình xây dựng cuộc sống mới đầy tự tin.", title: "Hành trình", currentPosition: "Vị trí hiện tại", words: "Từ vựng", sentences: "Câu", complete: "đã hoàn thành", recognized: "đã biết", mapLabel: "Bản đồ các giai đoạn cuộc sống", youAreHere: "Bạn đang ở đây", footerFirst: "Cuộc sống mới của bạn,", footerSecond: "tiến thêm một bước.", chooseEyebrow: "Chọn hành trình của bạn", chooseTitle: "Điều gì đưa bạn đến Canada?", chooseBody: "Chọn hành trình phù hợp nhất với bạn. Bạn có thể thay đổi sau.", reloadTitle: "Tải lại dữ liệu hành trình?", switchTitle: "Chuyển sang {{journey}}?", reloadBody: "Dữ liệu sẽ được tải lại và tiến độ cục bộ sẽ bị xóa.", confirmReload: "Xác nhận tải lại", confirmSwitch: "Xác nhận chuyển", lifeStage: "Giai đoạn cuộc sống", stageOverview: "Tổng quan giai đoạn", scenariosComplete: "tình huống đã hoàn thành", scenarios: "Tình huống", realLifeScenario: "Tình huống đời thực" },
    practice: { wordTitle: "Luyện từ vựng", wordEyebrow: "Xây dựng vốn từ vựng hằng ngày", wordHeading: "Từ vựng cho cuộc sống thực.", wordsPractised: "từ đã luyện", shuffled: "Đã xáo trộn", inOrder: "Theo thứ tự", reloadList: "Tải lại danh sách", word: "Từ", phrase: "Câu", listen: "Nghe", notKnown: "Chưa biết", skip: "Bỏ qua", known: "Đã biết", noWords: "Chưa có từ vựng. Kết nối mạng một lần để tải danh sách luyện tập.", noPhrases: "Chưa có câu luyện tập. Kết nối mạng một lần để tải danh sách.", reloadWordTitle: "Tải lại danh sách từ?", reloadSentenceTitle: "Tải lại danh sách câu?", reloadBody: "Danh sách mới sẽ thay thế danh sách đã lưu và xóa tiến độ cục bộ.", confirmReload: "Xác nhận tải lại" },
    scenario: { knowledge: "Kiến thức", vocabulary: "Từ vựng", conversation: "Hội thoại", review: "Ôn tập", sections: "Các phần của tình huống", previous: "Trước", next: "Tiếp", complete: "Đã hoàn thành tình huống", youDidIt: "Bạn làm được rồi!", completionBody: "Bạn đã sẵn sàng sử dụng hội thoại này trong đời thực. Hãy tiếp tục nhé!", continueNext: "Tiếp tục tình huống sau", chooseNext: "Chọn tình huống sau", returnJourney: "Quay lại hành trình", knowledgeEyebrow: "Biết trước khi bắt đầu", knowledgeHeading: "Chuẩn bị cho một cuộc trò chuyện tốt.", tipTitle: "Mẹo LifeStep", tipBody: "Bạn không cần hiểu mọi từ. Hãy nghe câu hỏi chính rồi trả lời từng ý một.", vocabularyEyebrow: "Từ vựng cho tình huống này", vocabularyHeading: "Chạm, nghe và biến chúng thành cách nói của bạn.", vocabularyPrompt: "Chạm vào từ để nghe", conversationEyebrow: "Luyện hội thoại", conversationHeading: "Làm cho tình huống trở nên quen thuộc.", fullDialogue: "Toàn bộ hội thoại", practiceMode: "Chế độ luyện tập", conversationPartner: "Người đối thoại", tapToListen: "Chạm vào tin nhắn để nghe", realLifePractice: "Luyện tập đời thực · Canada", line: "Dòng", playLine: "Phát dòng này", whatPractised: "Nội dung đã luyện", reviewPrompt: "Chạm vào từng câu khi bạn có thể nói câu đó một cách tự tin.", takeaway: "Điều cần nhớ" },
    common: { back: "Quay lại", close: "Đóng", clear: "Xóa", install: "Cài đặt LifeStep", practiceMenu: "Luyện tập", wordPractice: "Luyện từ vựng", sentencePractice: "Luyện câu", splashTagline: "Bước vào cuộc sống thực" },
  },
  pa: {
    journey: { study: "ਪੜ੍ਹਾਈ", work: "ਕੰਮ", family: "ਪਰਿਵਾਰ", studyBody: "ਪੜ੍ਹਾਈ ਅਤੇ ਰੋਜ਼ਾਨਾ ਜੀਵਨ ਲਈ ਭਰੋਸਾ ਬਣਾਓ।", workBody: "ਜੀਵਨ ਵਿੱਚ ਰਚੋ, ਕੰਮ ਲੱਭੋ ਅਤੇ ਆਪਣਾ ਕਰੀਅਰ ਵਧਾਓ।", familyBody: "ਆਪਣੇ ਪਰਿਵਾਰ ਲਈ ਭਰੋਸੇਮੰਦ ਨਵੀਂ ਜ਼ਿੰਦਗੀ ਬਣਾਓ।", title: "ਸਫ਼ਰ", currentPosition: "ਮੌਜੂਦਾ ਸਥਿਤੀ", words: "ਸ਼ਬਦ", sentences: "ਵਾਕ", complete: "ਪੂਰੇ", recognized: "ਜਾਣੇ", mapLabel: "ਜ਼ਿੰਦਗੀ ਦੇ ਪੜਾਵਾਂ ਦਾ ਨਕਸ਼ਾ", youAreHere: "ਤੁਸੀਂ ਇੱਥੇ ਹੋ", footerFirst: "ਤੁਹਾਡੀ ਨਵੀਂ ਜ਼ਿੰਦਗੀ,", footerSecond: "ਇੱਕ ਕਦਮ ਹੋਰ ਨੇੜੇ।", chooseEyebrow: "ਆਪਣਾ ਸਫ਼ਰ ਚੁਣੋ", chooseTitle: "ਤੁਹਾਨੂੰ ਕੈਨੇਡਾ ਕੀ ਲੈ ਕੇ ਆਇਆ?", chooseBody: "ਆਪਣੇ ਲਈ ਢੁਕਵਾਂ ਰਸਤਾ ਚੁਣੋ। ਤੁਸੀਂ ਬਾਅਦ ਵਿੱਚ ਬਦਲ ਸਕਦੇ ਹੋ।", reloadTitle: "ਸਫ਼ਰ ਦਾ ਡਾਟਾ ਦੁਬਾਰਾ ਲੋਡ ਕਰੀਏ?", switchTitle: "{{journey}} ਵੱਲ ਬਦਲੀਏ?", reloadBody: "ਚੁਣਿਆ ਡਾਟਾ ਦੁਬਾਰਾ ਲੋਡ ਹੋਵੇਗਾ ਅਤੇ ਸਥਾਨਕ ਤਰੱਕੀ ਮਿਟ ਜਾਵੇਗੀ।", confirmReload: "ਦੁਬਾਰਾ ਲੋਡ ਪੱਕਾ ਕਰੋ", confirmSwitch: "ਬਦਲਾਅ ਪੱਕਾ ਕਰੋ", lifeStage: "ਜ਼ਿੰਦਗੀ ਦਾ ਪੜਾਅ", stageOverview: "ਪੜਾਅ ਦਾ ਸਾਰ", scenariosComplete: "ਸਥਿਤੀਆਂ ਪੂਰੀਆਂ", scenarios: "ਸਥਿਤੀਆਂ", realLifeScenario: "ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀ ਸਥਿਤੀ" },
    practice: { wordTitle: "ਸ਼ਬਦ ਅਭਿਆਸ", wordEyebrow: "ਰੋਜ਼ਾਨਾ ਸ਼ਬਦ-ਭੰਡਾਰ ਬਣਾਓ", wordHeading: "ਅਸਲ ਜ਼ਿੰਦਗੀ ਲਈ ਸ਼ਬਦ।", wordsPractised: "ਸ਼ਬਦਾਂ ਦਾ ਅਭਿਆਸ", shuffled: "ਬੇਤਰਤੀਬ", inOrder: "ਕ੍ਰਮ ਵਿੱਚ", reloadList: "ਸੂਚੀ ਦੁਬਾਰਾ ਲੋਡ ਕਰੋ", word: "ਸ਼ਬਦ", phrase: "ਵਾਕ", listen: "ਸੁਣੋ", notKnown: "ਨਹੀਂ ਪਤਾ", skip: "ਛੱਡੋ", known: "ਪਤਾ ਹੈ", noWords: "ਹਾਲੇ ਕੋਈ ਸ਼ਬਦ ਉਪਲਬਧ ਨਹੀਂ। ਸੂਚੀ ਡਾਊਨਲੋਡ ਕਰਨ ਲਈ ਇੱਕ ਵਾਰ ਜੁੜੋ।", noPhrases: "ਹਾਲੇ ਕੋਈ ਵਾਕ ਉਪਲਬਧ ਨਹੀਂ। ਸੂਚੀ ਡਾਊਨਲੋਡ ਕਰਨ ਲਈ ਇੱਕ ਵਾਰ ਜੁੜੋ।", reloadWordTitle: "ਸ਼ਬਦਾਂ ਦੀ ਸੂਚੀ ਦੁਬਾਰਾ ਲੋਡ ਕਰੀਏ?", reloadSentenceTitle: "ਵਾਕਾਂ ਦੀ ਸੂਚੀ ਦੁਬਾਰਾ ਲੋਡ ਕਰੀਏ?", reloadBody: "ਨਵੀਂ ਸੂਚੀ ਸੁਰੱਖਿਅਤ ਸੂਚੀ ਦੀ ਥਾਂ ਲਵੇਗੀ ਅਤੇ ਸਥਾਨਕ ਤਰੱਕੀ ਮਿਟੇਗੀ।", confirmReload: "ਦੁਬਾਰਾ ਲੋਡ ਪੱਕਾ ਕਰੋ" },
    scenario: { knowledge: "ਗਿਆਨ", vocabulary: "ਸ਼ਬਦ-ਭੰਡਾਰ", conversation: "ਗੱਲਬਾਤ", review: "ਦੁਹਰਾਈ", sections: "ਸਥਿਤੀ ਦੇ ਭਾਗ", previous: "ਪਿਛਲਾ", next: "ਅਗਲਾ", complete: "ਸਥਿਤੀ ਪੂਰੀ", youDidIt: "ਤੁਸੀਂ ਕਰ ਲਿਆ!", completionBody: "ਤੁਸੀਂ ਇਹ ਗੱਲਬਾਤ ਅਸਲ ਜ਼ਿੰਦਗੀ ਵਿੱਚ ਵਰਤਣ ਲਈ ਤਿਆਰ ਹੋ। ਇਸੇ ਤਰ੍ਹਾਂ ਜਾਰੀ ਰੱਖੋ!", continueNext: "ਅਗਲੀ ਸਥਿਤੀ ਜਾਰੀ ਰੱਖੋ", chooseNext: "ਅਗਲੀ ਸਥਿਤੀ ਚੁਣੋ", returnJourney: "ਸਫ਼ਰ ਵੱਲ ਵਾਪਸ", knowledgeEyebrow: "ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ", knowledgeHeading: "ਚੰਗੀ ਗੱਲਬਾਤ ਲਈ ਤਿਆਰ ਹੋਵੋ।", tipTitle: "LifeStep ਸੁਝਾਅ", tipBody: "ਤੁਹਾਨੂੰ ਹਰ ਸ਼ਬਦ ਸਮਝਣ ਦੀ ਲੋੜ ਨਹੀਂ। ਮੁੱਖ ਸਵਾਲ ਸੁਣੋ ਅਤੇ ਇੱਕ ਵਾਰ ਵਿੱਚ ਇੱਕ ਵਿਚਾਰ ਦਾ ਜਵਾਬ ਦਿਓ।", vocabularyEyebrow: "ਇਸ ਮੌਕੇ ਲਈ ਸ਼ਬਦ", vocabularyHeading: "ਟੈਪ ਕਰੋ, ਸੁਣੋ ਅਤੇ ਇਨ੍ਹਾਂ ਨੂੰ ਆਪਣੀ ਬੋਲੀ ਬਣਾਓ।", vocabularyPrompt: "ਸੁਣਨ ਲਈ ਸ਼ਬਦ ਟੈਪ ਕਰੋ", conversationEyebrow: "ਗੱਲਬਾਤ ਦਾ ਅਭਿਆਸ", conversationHeading: "ਇਸ ਪਲ ਨੂੰ ਜਾਣ-ਪਛਾਣ ਵਾਲਾ ਬਣਾਓ।", fullDialogue: "ਪੂਰੀ ਗੱਲਬਾਤ", practiceMode: "ਅਭਿਆਸ ਮੋਡ", conversationPartner: "ਗੱਲਬਾਤ ਸਾਥੀ", tapToListen: "ਸੁਣਨ ਲਈ ਸੁਨੇਹਾ ਟੈਪ ਕਰੋ", realLifePractice: "ਅਸਲ ਜ਼ਿੰਦਗੀ ਦਾ ਅਭਿਆਸ · ਕੈਨੇਡਾ", line: "ਲਾਈਨ", playLine: "ਲਾਈਨ ਚਲਾਓ", whatPractised: "ਤੁਸੀਂ ਕੀ ਅਭਿਆਸ ਕੀਤਾ", reviewPrompt: "ਜਦੋਂ ਤੁਸੀਂ ਹਰ ਵਾਕ ਭਰੋਸੇ ਨਾਲ ਕਹਿ ਸਕੋ ਤਾਂ ਉਸਨੂੰ ਟੈਪ ਕਰੋ।", takeaway: "ਯਾਦ ਰੱਖੋ" },
    common: { back: "ਵਾਪਸ", close: "ਬੰਦ ਕਰੋ", clear: "ਸਾਫ਼ ਕਰੋ", install: "LifeStep ਇੰਸਟਾਲ ਕਰੋ", practiceMenu: "ਅਭਿਆਸ", wordPractice: "ਸ਼ਬਦ ਅਭਿਆਸ", sentencePractice: "ਵਾਕ ਅਭਿਆਸ", splashTagline: "ਅਸਲ ਜ਼ਿੰਦਗੀ ਵੱਲ ਕਦਮ" },
  },
};

const localeFallbacks: Record<Locale, LifeStepCopy> = {
  en,
  fr: en,
  es: en,
  ja: en,
  ko: en,
  pa: en,
  ru: en,
  vi: en,
  "zh-Hans": en,
  "zh-Hant": en,
};

const extras: Record<Locale, LifeStepExtras> = {
  en: { journey: { scenario: "Scenario", changePath: "Change path", choosePath: "Choose path", startJourney: "Start Your Journey", resumeJourney: "Continue Your Journey" }, practice: { offlinePractice: "Offline practice", sentenceTitle: "Sentence practice", sentenceEyebrow: "Say it with confidence", sentenceHeading: "Phrases you can use.", phrasesPractised: "phrases practised", wordProgress: "Word {{current}} of {{total}}", phraseProgress: "Phrase {{current}} of {{total}}" }, scenario: { nextScenario: "Next scenario", you: "You" }, common: { appUtilities: "App utilities" } },
  "zh-Hans": { journey: { scenario: "场景", changePath: "切换旅程", choosePath: "选择旅程", startJourney: "开始你的旅程", resumeJourney: "继续你的旅程" }, practice: { offlinePractice: "离线练习", sentenceTitle: "句子练习", sentenceEyebrow: "自信表达", sentenceHeading: "你可以使用的句子。", phrasesPractised: "个句子已练习", wordProgress: "单词 {{current}} / {{total}}", phraseProgress: "句子 {{current}} / {{total}}" }, scenario: { nextScenario: "下一个场景", you: "你" }, common: { appUtilities: "应用功能" } },
  "zh-Hant": { journey: { scenario: "場景", changePath: "切換旅程", choosePath: "選擇旅程", startJourney: "開始你的旅程", resumeJourney: "繼續你的旅程" }, practice: { offlinePractice: "離線練習", sentenceTitle: "句子練習", sentenceEyebrow: "自信表達", sentenceHeading: "你可以使用的句子。", phrasesPractised: "個句子已練習", wordProgress: "單字 {{current}} / {{total}}", phraseProgress: "句子 {{current}} / {{total}}" }, scenario: { nextScenario: "下一個場景", you: "你" }, common: { appUtilities: "應用程式功能" } },
  fr: { journey: { scenario: "Scénario", changePath: "Changer de parcours", choosePath: "Choisir un parcours", startJourney: "Commencez votre parcours", resumeJourney: "Continuez votre parcours" }, practice: { offlinePractice: "Pratique hors ligne", sentenceTitle: "Exercices de phrases", sentenceEyebrow: "Parlez avec assurance", sentenceHeading: "Des phrases à utiliser.", phrasesPractised: "phrases pratiquées", wordProgress: "Mot {{current}} sur {{total}}", phraseProgress: "Phrase {{current}} sur {{total}}" }, scenario: { nextScenario: "Scénario suivant", you: "Vous" }, common: { appUtilities: "Fonctions de l’application" } },
  es: { journey: { scenario: "Escenario", changePath: "Cambiar recorrido", choosePath: "Elegir recorrido", startJourney: "Comienza tu recorrido", resumeJourney: "Continúa tu recorrido" }, practice: { offlinePractice: "Práctica sin conexión", sentenceTitle: "Práctica de frases", sentenceEyebrow: "Habla con confianza", sentenceHeading: "Frases para usar.", phrasesPractised: "frases practicadas", wordProgress: "Palabra {{current}} de {{total}}", phraseProgress: "Frase {{current}} de {{total}}" }, scenario: { nextScenario: "Siguiente escenario", you: "Tú" }, common: { appUtilities: "Funciones de la aplicación" } },
  ja: { journey: { scenario: "シナリオ", changePath: "進路を変更", choosePath: "進路を選択", startJourney: "旅を始める", resumeJourney: "旅を続ける" }, practice: { offlinePractice: "オフライン練習", sentenceTitle: "文の練習", sentenceEyebrow: "自信を持って話す", sentenceHeading: "使えるフレーズ。", phrasesPractised: "フレーズを練習済み", wordProgress: "単語 {{current}} / {{total}}", phraseProgress: "フレーズ {{current}} / {{total}}" }, scenario: { nextScenario: "次のシナリオ", you: "あなた" }, common: { appUtilities: "アプリ機能" } },
  ko: { journey: { scenario: "상황", changePath: "경로 변경", choosePath: "경로 선택", startJourney: "여정을 시작하세요", resumeJourney: "여정을 계속하세요" }, practice: { offlinePractice: "오프라인 연습", sentenceTitle: "문장 연습", sentenceEyebrow: "자신 있게 말해 보세요", sentenceHeading: "바로 쓸 수 있는 문장입니다.", phrasesPractised: "문장 연습 완료", wordProgress: "단어 {{current}} / {{total}}", phraseProgress: "문장 {{current}} / {{total}}" }, scenario: { nextScenario: "다음 상황", you: "나" }, common: { appUtilities: "앱 기능" } },
  pa: { journey: { scenario: "ਸਥਿਤੀ", changePath: "ਰਸਤਾ ਬਦਲੋ", choosePath: "ਰਸਤਾ ਚੁਣੋ", startJourney: "ਆਪਣਾ ਸਫ਼ਰ ਸ਼ੁਰੂ ਕਰੋ", resumeJourney: "ਆਪਣਾ ਸਫ਼ਰ ਜਾਰੀ ਰੱਖੋ" }, practice: { offlinePractice: "ਆਫਲਾਈਨ ਅਭਿਆਸ", sentenceTitle: "ਵਾਕ ਅਭਿਆਸ", sentenceEyebrow: "ਭਰੋਸੇ ਨਾਲ ਬੋਲੋ", sentenceHeading: "ਵਰਤਣ ਲਈ ਵਾਕ।", phrasesPractised: "ਵਾਕਾਂ ਦਾ ਅਭਿਆਸ", wordProgress: "ਸ਼ਬਦ {{current}} / {{total}}", phraseProgress: "ਵਾਕ {{current}} / {{total}}" }, scenario: { nextScenario: "ਅਗਲੀ ਸਥਿਤੀ", you: "ਤੁਸੀਂ" }, common: { appUtilities: "ਐਪ ਫੰਕਸ਼ਨ" } },
  ru: { journey: { scenario: "Сценарий", changePath: "Сменить путь", choosePath: "Выбрать путь", startJourney: "Начать свой путь", resumeJourney: "Продолжить свой путь" }, practice: { offlinePractice: "Офлайн-практика", sentenceTitle: "Практика фраз", sentenceEyebrow: "Говорите уверенно", sentenceHeading: "Фразы для жизни.", phrasesPractised: "фраз отработано", wordProgress: "Слово {{current}} из {{total}}", phraseProgress: "Фраза {{current}} из {{total}}" }, scenario: { nextScenario: "Следующий сценарий", you: "Вы" }, common: { appUtilities: "Функции приложения" } },
  vi: { journey: { scenario: "Tình huống", changePath: "Đổi hành trình", choosePath: "Chọn hành trình", startJourney: "Bắt đầu hành trình", resumeJourney: "Tiếp tục hành trình" }, practice: { offlinePractice: "Luyện tập ngoại tuyến", sentenceTitle: "Luyện câu", sentenceEyebrow: "Nói thật tự tin", sentenceHeading: "Những câu bạn có thể dùng.", phrasesPractised: "câu đã luyện", wordProgress: "Từ {{current}} / {{total}}", phraseProgress: "Câu {{current}} / {{total}}" }, scenario: { nextScenario: "Tình huống tiếp theo", you: "Bạn" }, common: { appUtilities: "Tiện ích ứng dụng" } },
};

export function getLifeStepCopy(locale: Locale): ResolvedLifeStepCopy {
  const base = translations[locale] ?? localeFallbacks[locale];
  const localeExtras = extras[locale] ?? extras.en;
  return {
    ...base,
    journey: { ...base.journey, ...localeExtras.journey },
    practice: { ...base.practice, ...localeExtras.practice },
    scenario: { ...base.scenario, ...localeExtras.scenario },
    common: { ...base.common, ...localeExtras.common },
  };
}
