export type LifeStepHomeContent = {
  title: string;
  seoTitle: string;
  seoDescription: string;
  intro: string;
  getStarted: string;
  explore: string;
  themeLabel: string;
  featuresKicker: string;
  faqNav: string;
  privacyNav: string;
  termsNav: string;
  launchApp: string;
  footer: string;
  metrics: Array<{ value: string; label: string }>;
  features: Array<{ eyebrow: string; title: string; body: string; tags: string[]; accent: string }>;
  faq: Array<{ question: string; answer: string }>;
};

export type LifeStepAppCopy = {
  back: string; about: string; settings: string; messages: string; journey: string;
  explore: string; start: string; resume: string; restart: string; progress: string;
  completed: string; inProgress: string; notStarted: string; loading: string; offline: string;
};

const features = (values: Array<[string, string, string, string[]]>) => values.map(([eyebrow, title, body, tags], index) => ({
  eyebrow, title, body, tags, accent: ["red", "blue", "lime", "orange", "red", "blue"][index],
}));

export const lifeStepHome = {
  en: {
    title: "LifeStep - Practice Real-Life English", seoTitle: "LifeStep - Practice Real-Life English", seoDescription: "Interactive English conversations that prepare Canadian newcomers for real-life situations.",
    intro: "Practise the conversations you need to arrive, settle, work, study, and feel at home in Canada.", getStarted: "Take your first step", explore: "See how it works", themeLabel: "Theme", featuresKicker: "How LifeStep works", faqNav: "FAQ", privacyNav: "Privacy Policy", termsNav: "Terms of Use", launchApp: "Open LifeStep", footer: "Real-life English for your new life in Canada.",
    metrics: [{ value: "10", label: "Languages" }, { value: "12", label: "Life stages" }, { value: "4", label: "Learning steps" }, { value: "24/7", label: "Practice anytime" }],
    features: features([["01 / Journey", "Follow real life, step by step", "A visual journey turns important newcomer moments into a clear path you can explore at your pace.", ["Study", "Work", "Family"]], ["02 / Learn", "Know what to expect", "Build context and vocabulary before a real conversation begins.", ["Knowledge", "Vocabulary"]], ["03 / Conversation", "Listen, repeat, and respond", "Hear natural voices and practise a complete dialogue or move through it one line at a time.", ["Natural voices", "Bilingual dialogue"]], ["04 / Review", "Make the language yours", "Review key phrases, check your confidence, and complete each real-life scenario.", ["Key phrases", "Progress"]], ["05 / Personal", "A path shaped around you", "Choose study, work, or family and focus on the situations most useful to your life.", ["Your pace", "Your journey"]], ["06 / Push", "Keep your next step close", "Optional notifications and a message center help you return to the right moment.", ["Web Push", "Message center"]]]),
    faq: [{ question: "Who is LifeStep for?", answer: "LifeStep is designed for newcomers preparing for everyday life, study, work, and family situations in Canada." }, { question: "Can I change the language and theme?", answer: "Yes. LifeStep supports ten interface languages plus light, dark, and system themes." }, { question: "How does conversation practice work?", answer: "Read the complete bilingual dialogue or practise one line at a time with natural synthesized voices." }],
  },
  fr: {
    title: "LifeStep - Pratiquez l’anglais de la vie réelle", seoTitle: "LifeStep - Pratiquez l’anglais de la vie réelle", seoDescription: "Des conversations interactives en anglais pour préparer les nouveaux arrivants à la vie au Canada.", intro: "Pratiquez les conversations utiles pour arriver, vous installer, travailler, étudier et vous sentir chez vous au Canada.", getStarted: "Faites le premier pas", explore: "Voir le fonctionnement", themeLabel: "Thème", featuresKicker: "Comment fonctionne LifeStep", faqNav: "FAQ", privacyNav: "Politique de confidentialité", termsNav: "Conditions d’utilisation", launchApp: "Ouvrir LifeStep", footer: "L’anglais de la vie réelle pour votre nouvelle vie au Canada.",
    metrics: [{ value: "10", label: "Langues" }, { value: "12", label: "Étapes de vie" }, { value: "4", label: "Étapes d’apprentissage" }, { value: "24/7", label: "Pratique à tout moment" }],
    features: features([["01 / Parcours", "Suivez la vraie vie, pas à pas", "Un parcours visuel transforme les moments importants en un chemin clair.", ["Études", "Travail", "Famille"]], ["02 / Apprendre", "Sachez à quoi vous attendre", "Découvrez le contexte et le vocabulaire avant la conversation.", ["Connaissances", "Vocabulaire"]], ["03 / Conversation", "Écoutez, répétez, répondez", "Écoutez des voix naturelles et pratiquez le dialogue complet ou phrase par phrase.", ["Voix naturelles", "Dialogue bilingue"]], ["04 / Révision", "Appropriez-vous la langue", "Révisez les phrases clés et terminez chaque scénario.", ["Phrases clés", "Progression"]], ["05 / Personnel", "Un parcours fait pour vous", "Choisissez études, travail ou famille.", ["Votre rythme", "Votre parcours"]], ["06 / Notifications", "Gardez la prochaine étape à portée", "Les notifications facultatives vous ramènent au bon moment.", ["Web Push", "Messages"]]]),
    faq: [{ question: "À qui s’adresse LifeStep ?", answer: "Aux nouveaux arrivants qui se préparent à la vie quotidienne, aux études, au travail et à la famille au Canada." }, { question: "Puis-je changer la langue et le thème ?", answer: "Oui. LifeStep prend en charge dix langues ainsi que les thèmes clair, sombre et système." }, { question: "Comment fonctionne la pratique ?", answer: "Lisez le dialogue bilingue ou avancez phrase par phrase avec des voix naturelles." }],
  },
  "zh-Hans": {
    title: "LifeStep - 练习真实生活英语", seoTitle: "LifeStep - 练习真实生活英语", seoDescription: "通过互动英语对话，帮助加拿大新移民为真实生活场景做好准备。", intro: "练习抵达、安顿、学习、工作以及融入加拿大生活时真正需要的对话。", getStarted: "迈出第一步", explore: "了解使用方式", themeLabel: "主题", featuresKicker: "LifeStep 如何使用", faqNav: "常见问题", privacyNav: "隐私政策", termsNav: "使用条款", launchApp: "打开 LifeStep", footer: "为你的加拿大新生活练习真实英语。",
    metrics: [{ value: "10", label: "界面语言" }, { value: "12", label: "人生阶段" }, { value: "4", label: "学习步骤" }, { value: "24/7", label: "随时练习" }],
    features: features([["01 / 旅程", "跟随真实生活，一步一步前进", "游戏地图把新移民的重要时刻整理成清晰、可探索的路径。", ["学习", "工作", "家庭"]], ["02 / 学习", "提前知道会发生什么", "在真实对话开始前掌握背景知识和实用词汇。", ["知识", "词汇"]], ["03 / 对话", "听、跟读、再回应", "使用自然语音练习完整对话，或逐句播放和练习。", ["自然语音", "双语对话"]], ["04 / 复习", "把英语真正变成自己的", "复习关键句、确认掌握程度并完成每个场景。", ["关键句", "学习进度"]], ["05 / 个性化", "围绕你的生活规划路径", "选择学习、工作或家庭，优先练习对你最有用的场景。", ["你的节奏", "你的旅程"]], ["06 / 通知", "不错过下一步", "可选通知和消息中心帮助你随时回到当前进度。", ["Web Push", "消息中心"]]]),
    faq: [{ question: "LifeStep 适合谁？", answer: "适合正在准备加拿大日常生活、学习、工作和家庭场景的新移民。" }, { question: "可以更换语言和主题吗？", answer: "可以。LifeStep 支持十种界面语言，以及浅色、深色和跟随系统主题。" }, { question: "对话练习如何使用？", answer: "你可以查看完整双语对话，也可以使用自然合成语音逐句练习。" }],
  },
  "zh-Hant": {
    title: "LifeStep - 練習真實生活英語", seoTitle: "LifeStep - 練習真實生活英語", seoDescription: "透過互動英語對話，幫助加拿大新移民為真實生活場景做好準備。", intro: "練習抵達、安頓、學習、工作以及融入加拿大生活時真正需要的對話。", getStarted: "踏出第一步", explore: "了解使用方式", themeLabel: "主題", featuresKicker: "LifeStep 如何使用", faqNav: "常見問題", privacyNav: "隱私政策", termsNav: "使用條款", launchApp: "開啟 LifeStep", footer: "為你的加拿大新生活練習真實英語。",
    metrics: [{ value: "10", label: "介面語言" }, { value: "12", label: "人生階段" }, { value: "4", label: "學習步驟" }, { value: "24/7", label: "隨時練習" }],
    features: features([["01 / 旅程", "跟隨真實生活，一步一步前進", "遊戲地圖把新移民的重要時刻整理成清晰路徑。", ["學習", "工作", "家庭"]], ["02 / 學習", "提前知道會發生什麼", "在真實對話開始前掌握背景知識和實用詞彙。", ["知識", "詞彙"]], ["03 / 對話", "聽、跟讀、再回應", "使用自然語音練習完整對話，或逐句播放。", ["自然語音", "雙語對話"]], ["04 / 複習", "把英語真正變成自己的", "複習關鍵句並完成每個場景。", ["關鍵句", "學習進度"]], ["05 / 個人化", "圍繞你的生活規劃路徑", "選擇學習、工作或家庭。", ["你的節奏", "你的旅程"]], ["06 / 通知", "不錯過下一步", "可選通知和訊息中心幫助你回到進度。", ["Web Push", "訊息中心"]]]),
    faq: [{ question: "LifeStep 適合誰？", answer: "適合正在準備加拿大日常生活、學習、工作和家庭場景的新移民。" }, { question: "可以更換語言和主題嗎？", answer: "可以。LifeStep 支援十種介面語言及淺色、深色和系統主題。" }, { question: "對話練習如何使用？", answer: "查看完整雙語對話，或使用自然合成語音逐句練習。" }],
  },
  es: {
    title: "LifeStep - Practica inglés para la vida real", seoTitle: "LifeStep - Practica inglés para la vida real", seoDescription: "Conversaciones interactivas en inglés para preparar a los recién llegados a la vida en Canadá.", intro: "Practica las conversaciones que necesitas para llegar, instalarte, estudiar, trabajar y sentirte en casa en Canadá.", getStarted: "Da tu primer paso", explore: "Cómo funciona", themeLabel: "Tema", featuresKicker: "Cómo funciona LifeStep", faqNav: "Preguntas", privacyNav: "Privacidad", termsNav: "Condiciones", launchApp: "Abrir LifeStep", footer: "Inglés para la vida real en tu nueva vida en Canadá.",
    metrics: [{ value: "10", label: "Idiomas" }, { value: "12", label: "Etapas de vida" }, { value: "4", label: "Pasos de aprendizaje" }, { value: "24/7", label: "Practica cuando quieras" }],
    features: features([["01 / Recorrido", "Sigue la vida real, paso a paso", "Un mapa visual convierte momentos importantes en un camino claro.", ["Estudio", "Trabajo", "Familia"]], ["02 / Aprende", "Sabe qué esperar", "Aprende el contexto y el vocabulario antes de conversar.", ["Conocimiento", "Vocabulario"]], ["03 / Conversación", "Escucha, repite y responde", "Practica diálogos completos o frase por frase con voces naturales.", ["Voces naturales", "Diálogo bilingüe"]], ["04 / Repaso", "Haz tuyo el idioma", "Repasa frases clave y completa cada escenario.", ["Frases clave", "Progreso"]], ["05 / Personal", "Un camino hecho para ti", "Elige estudio, trabajo o familia.", ["Tu ritmo", "Tu recorrido"]], ["06 / Avisos", "Mantén cerca el siguiente paso", "Las notificaciones opcionales te ayudan a continuar.", ["Web Push", "Mensajes"]]]),
    faq: [{ question: "¿Para quién es LifeStep?", answer: "Para recién llegados que se preparan para la vida diaria, el estudio, el trabajo y la familia en Canadá." }, { question: "¿Puedo cambiar idioma y tema?", answer: "Sí. LifeStep ofrece diez idiomas y temas claro, oscuro y del sistema." }, { question: "¿Cómo se practica la conversación?", answer: "Lee el diálogo bilingüe completo o practica frase por frase con voces naturales." }],
  },
  ja: {
    title: "LifeStep - 実生活の英語を練習", seoTitle: "LifeStep - 実生活の英語を練習", seoDescription: "カナダでの実生活に備えるためのインタラクティブな英会話練習。", intro: "カナダへの到着、生活、留学、仕事に必要な会話を練習しましょう。", getStarted: "最初の一歩", explore: "使い方を見る", themeLabel: "テーマ", featuresKicker: "LifeStep の使い方", faqNav: "よくある質問", privacyNav: "プライバシー", termsNav: "利用規約", launchApp: "LifeStep を開く", footer: "カナダでの新生活に役立つ実践英語。",
    metrics: [{ value: "10", label: "言語" }, { value: "12", label: "ライフステージ" }, { value: "4", label: "学習ステップ" }, { value: "24/7", label: "いつでも練習" }],
    features: features([["01 / 旅", "実生活を一歩ずつ", "新生活の大切な場面を見やすいマップで進みます。", ["留学", "仕事", "家族"]], ["02 / 学ぶ", "場面を先に理解", "会話の前に背景と語彙を学びます。", ["知識", "語彙"]], ["03 / 会話", "聞いて、繰り返して、答える", "自然な音声で会話全体または一文ずつ練習します。", ["自然な音声", "二言語会話"]], ["04 / 復習", "英語を自分のものに", "重要表現を復習して場面を完了します。", ["重要表現", "進捗"]], ["05 / 個別", "あなたに合う道", "留学、仕事、家族から選べます。", ["自分のペース", "自分の旅"]], ["06 / 通知", "次の一歩を忘れない", "通知とメッセージで学習に戻れます。", ["Web Push", "メッセージ"]]]),
    faq: [{ question: "LifeStep は誰向けですか？", answer: "カナダでの日常、留学、仕事、家族生活に備える新移民向けです。" }, { question: "言語とテーマは変更できますか？", answer: "はい。10言語とライト、ダーク、システムテーマに対応します。" }, { question: "会話練習はどう進めますか？", answer: "二言語の会話全体、または自然な合成音声で一文ずつ練習できます。" }],
  },
  ko: {
    title: "LifeStep - 실생활 영어 연습", seoTitle: "LifeStep - 실생활 영어 연습", seoDescription: "캐나다 새 이민자의 실생활을 준비하는 대화형 영어 회화 연습.", intro: "캐나다 도착, 정착, 학업, 직장생활에 필요한 대화를 연습하세요.", getStarted: "첫걸음 시작", explore: "사용 방법", themeLabel: "테마", featuresKicker: "LifeStep 사용 방법", faqNav: "자주 묻는 질문", privacyNav: "개인정보", termsNav: "이용약관", launchApp: "LifeStep 열기", footer: "캐나다의 새로운 삶을 위한 실생활 영어.",
    metrics: [{ value: "10", label: "언어" }, { value: "12", label: "생활 단계" }, { value: "4", label: "학습 단계" }, { value: "24/7", label: "언제든 연습" }],
    features: features([["01 / 여정", "실생활을 한 걸음씩", "중요한 새 이민자 경험을 명확한 지도에서 탐색합니다.", ["학업", "직장", "가족"]], ["02 / 학습", "상황을 미리 이해하세요", "대화 전에 배경과 어휘를 익힙니다.", ["지식", "어휘"]], ["03 / 대화", "듣고, 따라 하고, 응답하세요", "자연스러운 음성으로 전체 대화 또는 한 문장씩 연습합니다.", ["자연스러운 음성", "이중 언어"]], ["04 / 복습", "영어를 내 것으로", "핵심 문장을 복습하고 상황을 완료합니다.", ["핵심 문장", "진행률"]], ["05 / 맞춤", "나에게 맞는 경로", "학업, 직장 또는 가족을 선택합니다.", ["나의 속도", "나의 여정"]], ["06 / 알림", "다음 단계를 가까이", "선택 알림으로 학습을 이어갑니다.", ["Web Push", "메시지"]]]),
    faq: [{ question: "LifeStep은 누구를 위한 앱인가요?", answer: "캐나다 일상, 학업, 직장, 가족생활을 준비하는 새 이민자를 위한 앱입니다." }, { question: "언어와 테마를 바꿀 수 있나요?", answer: "네. 10개 언어와 라이트, 다크, 시스템 테마를 지원합니다." }, { question: "대화 연습은 어떻게 하나요?", answer: "이중 언어 대화 전체 또는 자연스러운 합성 음성으로 한 문장씩 연습합니다." }],
  },
  ru: {
    title: "LifeStep — английский для реальной жизни", seoTitle: "LifeStep — английский для реальной жизни", seoDescription: "Интерактивные диалоги для подготовки новых жителей к жизни в Канаде.", intro: "Практикуйте разговоры, необходимые для приезда, учёбы, работы и жизни в Канаде.", getStarted: "Сделать первый шаг", explore: "Как это работает", themeLabel: "Тема", featuresKicker: "Как работает LifeStep", faqNav: "Вопросы", privacyNav: "Конфиденциальность", termsNav: "Условия", launchApp: "Открыть LifeStep", footer: "Практический английский для новой жизни в Канаде.",
    metrics: [{ value: "10", label: "Языков" }, { value: "12", label: "Этапов жизни" }, { value: "4", label: "Шага обучения" }, { value: "24/7", label: "Практика всегда" }],
    features: features([["01 / Путь", "Реальная жизнь шаг за шагом", "Наглядная карта превращает важные ситуации в понятный путь.", ["Учёба", "Работа", "Семья"]], ["02 / Учёба", "Знайте, чего ожидать", "Изучите контекст и слова до начала разговора.", ["Знания", "Словарь"]], ["03 / Диалог", "Слушайте, повторяйте, отвечайте", "Практикуйте весь диалог или по одной фразе с естественными голосами.", ["Естественные голоса", "Два языка"]], ["04 / Повторение", "Сделайте язык своим", "Повторите ключевые фразы и завершите сценарий.", ["Ключевые фразы", "Прогресс"]], ["05 / Личное", "Путь для вас", "Выберите учёбу, работу или семью.", ["Ваш темп", "Ваш путь"]], ["06 / Уведомления", "Следующий шаг рядом", "Необязательные уведомления помогают продолжить.", ["Web Push", "Сообщения"]]]),
    faq: [{ question: "Для кого LifeStep?", answer: "Для новых жителей, готовящихся к повседневной жизни, учёбе, работе и семье в Канаде." }, { question: "Можно сменить язык и тему?", answer: "Да. Доступны десять языков и светлая, тёмная и системная темы." }, { question: "Как проходит практика диалога?", answer: "Читайте весь двуязычный диалог или практикуйте по фразе с естественными голосами." }],
  },
  vi: {
    title: "LifeStep - Luyện tiếng Anh đời thực", seoTitle: "LifeStep - Luyện tiếng Anh đời thực", seoDescription: "Hội thoại tiếng Anh tương tác giúp người mới đến chuẩn bị cho cuộc sống tại Canada.", intro: "Luyện những cuộc hội thoại cần thiết khi đến, ổn định, học tập và làm việc tại Canada.", getStarted: "Bước đầu tiên", explore: "Cách hoạt động", themeLabel: "Giao diện", featuresKicker: "LifeStep hoạt động thế nào", faqNav: "Câu hỏi", privacyNav: "Quyền riêng tư", termsNav: "Điều khoản", launchApp: "Mở LifeStep", footer: "Tiếng Anh đời thực cho cuộc sống mới tại Canada.",
    metrics: [{ value: "10", label: "Ngôn ngữ" }, { value: "12", label: "Giai đoạn cuộc sống" }, { value: "4", label: "Bước học" }, { value: "24/7", label: "Luyện mọi lúc" }],
    features: features([["01 / Hành trình", "Theo đời thực, từng bước", "Bản đồ trực quan biến các tình huống quan trọng thành lộ trình rõ ràng.", ["Học tập", "Công việc", "Gia đình"]], ["02 / Học", "Biết trước điều sẽ xảy ra", "Học bối cảnh và từ vựng trước khi hội thoại.", ["Kiến thức", "Từ vựng"]], ["03 / Hội thoại", "Nghe, lặp lại và trả lời", "Luyện cả đoạn hoặc từng câu với giọng đọc tự nhiên.", ["Giọng tự nhiên", "Song ngữ"]], ["04 / Ôn tập", "Biến ngôn ngữ thành của bạn", "Ôn cụm từ chính và hoàn thành tình huống.", ["Cụm từ", "Tiến độ"]], ["05 / Cá nhân", "Lộ trình dành cho bạn", "Chọn học tập, công việc hoặc gia đình.", ["Nhịp của bạn", "Hành trình của bạn"]], ["06 / Thông báo", "Giữ bước tiếp theo bên mình", "Thông báo tùy chọn giúp bạn tiếp tục.", ["Web Push", "Tin nhắn"]]]),
    faq: [{ question: "LifeStep dành cho ai?", answer: "Dành cho người mới đến chuẩn bị cho đời sống, học tập, công việc và gia đình tại Canada." }, { question: "Có thể đổi ngôn ngữ và giao diện không?", answer: "Có. LifeStep hỗ trợ mười ngôn ngữ và giao diện sáng, tối hoặc theo hệ thống." }, { question: "Luyện hội thoại như thế nào?", answer: "Đọc toàn bộ hội thoại song ngữ hoặc luyện từng câu với giọng tổng hợp tự nhiên." }],
  },
  pa: {
    title: "LifeStep - ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀ ਅੰਗਰੇਜ਼ੀ ਦਾ ਅਭਿਆਸ", seoTitle: "LifeStep - ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀ ਅੰਗਰੇਜ਼ੀ ਦਾ ਅਭਿਆਸ", seoDescription: "ਕੈਨੇਡਾ ਵਿੱਚ ਨਵੀਂ ਜ਼ਿੰਦਗੀ ਲਈ ਇੰਟਰਐਕਟਿਵ ਅੰਗਰੇਜ਼ੀ ਗੱਲਬਾਤ।", intro: "ਕੈਨੇਡਾ ਪਹੁੰਚਣ, ਵੱਸਣ, ਪੜ੍ਹਨ ਅਤੇ ਕੰਮ ਕਰਨ ਲਈ ਲੋੜੀਂਦੀਆਂ ਗੱਲਬਾਤਾਂ ਦਾ ਅਭਿਆਸ ਕਰੋ।", getStarted: "ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ", explore: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ", themeLabel: "ਥੀਮ", featuresKicker: "LifeStep ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ", faqNav: "ਸਵਾਲ", privacyNav: "ਪਰਦੇਦਾਰੀ", termsNav: "ਸ਼ਰਤਾਂ", launchApp: "LifeStep ਖੋਲ੍ਹੋ", footer: "ਕੈਨੇਡਾ ਵਿੱਚ ਨਵੀਂ ਜ਼ਿੰਦਗੀ ਲਈ ਅਸਲ ਅੰਗਰੇਜ਼ੀ।",
    metrics: [{ value: "10", label: "ਭਾਸ਼ਾਵਾਂ" }, { value: "12", label: "ਜੀਵਨ ਪੜਾਅ" }, { value: "4", label: "ਸਿੱਖਣ ਦੇ ਕਦਮ" }, { value: "24/7", label: "ਕਦੇ ਵੀ ਅਭਿਆਸ" }],
    features: features([["01 / ਯਾਤਰਾ", "ਅਸਲ ਜ਼ਿੰਦਗੀ, ਕਦਮ ਦਰ ਕਦਮ", "ਇੱਕ ਵਿਜ਼ੂਅਲ ਨਕਸ਼ਾ ਮਹੱਤਵਪੂਰਨ ਪਲਾਂ ਨੂੰ ਸਾਫ਼ ਰਸਤੇ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।", ["ਪੜ੍ਹਾਈ", "ਕੰਮ", "ਪਰਿਵਾਰ"]], ["02 / ਸਿੱਖੋ", "ਪਹਿਲਾਂ ਜਾਣੋ ਕੀ ਹੋਵੇਗਾ", "ਗੱਲਬਾਤ ਤੋਂ ਪਹਿਲਾਂ ਸੰਦਰਭ ਅਤੇ ਸ਼ਬਦਾਵਲੀ ਸਿੱਖੋ।", ["ਗਿਆਨ", "ਸ਼ਬਦਾਵਲੀ"]], ["03 / ਗੱਲਬਾਤ", "ਸੁਣੋ, ਦੁਹਰਾਓ, ਜਵਾਬ ਦਿਓ", "ਕੁਦਰਤੀ ਆਵਾਜ਼ਾਂ ਨਾਲ ਪੂਰੀ ਜਾਂ ਲਾਈਨ-ਦਰ-ਲਾਈਨ ਗੱਲਬਾਤ ਕਰੋ।", ["ਕੁਦਰਤੀ ਆਵਾਜ਼", "ਦੋ ਭਾਸ਼ਾਵਾਂ"]], ["04 / ਸਮੀਖਿਆ", "ਭਾਸ਼ਾ ਨੂੰ ਆਪਣਾ ਬਣਾਓ", "ਮੁੱਖ ਵਾਕਾਂਸ਼ ਦੁਹਰਾਓ ਅਤੇ ਦ੍ਰਿਸ਼ ਪੂਰਾ ਕਰੋ।", ["ਮੁੱਖ ਵਾਕ", "ਤਰੱਕੀ"]], ["05 / ਨਿੱਜੀ", "ਤੁਹਾਡੇ ਲਈ ਰਸਤਾ", "ਪੜ੍ਹਾਈ, ਕੰਮ ਜਾਂ ਪਰਿਵਾਰ ਚੁਣੋ।", ["ਤੁਹਾਡੀ ਰਫ਼ਤਾਰ", "ਤੁਹਾਡੀ ਯਾਤਰਾ"]], ["06 / ਸੂਚਨਾ", "ਅਗਲਾ ਕਦਮ ਨੇੜੇ ਰੱਖੋ", "ਚੋਣਵੀਂ ਸੂਚਨਾਵਾਂ ਅਭਿਆਸ ਜਾਰੀ ਰੱਖਦੀਆਂ ਹਨ।", ["Web Push", "ਸੁਨੇਹੇ"]]]),
    faq: [{ question: "LifeStep ਕਿਸ ਲਈ ਹੈ?", answer: "ਕੈਨੇਡਾ ਵਿੱਚ ਰੋਜ਼ਾਨਾ ਜੀਵਨ, ਪੜ੍ਹਾਈ, ਕੰਮ ਅਤੇ ਪਰਿਵਾਰ ਲਈ ਤਿਆਰ ਹੋ ਰਹੇ ਨਵੇਂ ਲੋਕਾਂ ਲਈ।" }, { question: "ਕੀ ਭਾਸ਼ਾ ਅਤੇ ਥੀਮ ਬਦਲ ਸਕਦੇ ਹਾਂ?", answer: "ਹਾਂ। ਦਸ ਭਾਸ਼ਾਵਾਂ ਅਤੇ ਲਾਈਟ, ਡਾਰਕ ਜਾਂ ਸਿਸਟਮ ਥੀਮ ਉਪਲਬਧ ਹਨ।" }, { question: "ਗੱਲਬਾਤ ਦਾ ਅਭਿਆਸ ਕਿਵੇਂ ਹੁੰਦਾ ਹੈ?", answer: "ਦੋ-ਭਾਸ਼ਾਈ ਗੱਲਬਾਤ ਪੜ੍ਹੋ ਜਾਂ ਕੁਦਰਤੀ ਆਵਾਜ਼ ਨਾਲ ਇੱਕ-ਇੱਕ ਲਾਈਨ ਦਾ ਅਭਿਆਸ ਕਰੋ।" }],
  },
} satisfies Record<string, LifeStepHomeContent>;

export const lifeStepAppCopy: Record<string, LifeStepAppCopy> = {
  en: { back: "Back", about: "About", settings: "Settings", messages: "Messages", journey: "Your journey", explore: "Explore", start: "Start exploring", resume: "Continue exploring", restart: "Explore again", progress: "Progress", completed: "Completed", inProgress: "In progress", notStarted: "Not started", loading: "Preparing your next step…", offline: "Showing a practice preview while the service reconnects." },
  fr: { back: "Retour", about: "À propos", settings: "Réglages", messages: "Messages", journey: "Votre parcours", explore: "Explorer", start: "Commencer", resume: "Continuer", restart: "Recommencer", progress: "Progression", completed: "Terminé", inProgress: "En cours", notStarted: "Pas commencé", loading: "Préparation de la prochaine étape…", offline: "Aperçu affiché pendant la reconnexion." },
  "zh-Hans": { back: "返回", about: "关于", settings: "设置", messages: "消息中心", journey: "你的旅程", explore: "探索", start: "开始探索", resume: "继续探索", restart: "重新探索", progress: "进度", completed: "已完成", inProgress: "进行中", notStarted: "未开始", loading: "正在准备下一步…", offline: "服务连接中，当前展示练习预览。" },
  "zh-Hant": { back: "返回", about: "關於", settings: "設定", messages: "訊息中心", journey: "你的旅程", explore: "探索", start: "開始探索", resume: "繼續探索", restart: "重新探索", progress: "進度", completed: "已完成", inProgress: "進行中", notStarted: "未開始", loading: "正在準備下一步…", offline: "服務連線中，目前顯示練習預覽。" },
  es: { back: "Atrás", about: "Acerca de", settings: "Ajustes", messages: "Mensajes", journey: "Tu recorrido", explore: "Explorar", start: "Empezar", resume: "Continuar", restart: "Explorar de nuevo", progress: "Progreso", completed: "Completado", inProgress: "En progreso", notStarted: "Sin empezar", loading: "Preparando tu próximo paso…", offline: "Mostrando una vista previa mientras se reconecta." },
  ja: { back: "戻る", about: "概要", settings: "設定", messages: "メッセージ", journey: "あなたの旅", explore: "探索", start: "探索を始める", resume: "探索を続ける", restart: "もう一度探索", progress: "進捗", completed: "完了", inProgress: "進行中", notStarted: "未開始", loading: "次のステップを準備中…", offline: "再接続中のためプレビューを表示しています。" },
  ko: { back: "뒤로", about: "정보", settings: "설정", messages: "메시지", journey: "나의 여정", explore: "탐색", start: "탐색 시작", resume: "계속 탐색", restart: "다시 탐색", progress: "진행률", completed: "완료", inProgress: "진행 중", notStarted: "시작 전", loading: "다음 단계를 준비 중…", offline: "다시 연결하는 동안 미리보기를 표시합니다." },
  ru: { back: "Назад", about: "О приложении", settings: "Настройки", messages: "Сообщения", journey: "Ваш путь", explore: "Изучить", start: "Начать", resume: "Продолжить", restart: "Начать заново", progress: "Прогресс", completed: "Завершено", inProgress: "В процессе", notStarted: "Не начато", loading: "Готовим следующий шаг…", offline: "Показан предварительный режим во время подключения." },
  vi: { back: "Quay lại", about: "Giới thiệu", settings: "Cài đặt", messages: "Tin nhắn", journey: "Hành trình", explore: "Khám phá", start: "Bắt đầu", resume: "Tiếp tục", restart: "Khám phá lại", progress: "Tiến độ", completed: "Đã hoàn thành", inProgress: "Đang thực hiện", notStarted: "Chưa bắt đầu", loading: "Đang chuẩn bị bước tiếp theo…", offline: "Hiển thị bản xem trước khi kết nối lại." },
  pa: { back: "ਵਾਪਸ", about: "ਜਾਣਕਾਰੀ", settings: "ਸੈਟਿੰਗਾਂ", messages: "ਸੁਨੇਹੇ", journey: "ਤੁਹਾਡੀ ਯਾਤਰਾ", explore: "ਖੋਜੋ", start: "ਸ਼ੁਰੂ ਕਰੋ", resume: "ਜਾਰੀ ਰੱਖੋ", restart: "ਮੁੜ ਸ਼ੁਰੂ", progress: "ਤਰੱਕੀ", completed: "ਪੂਰਾ", inProgress: "ਜਾਰੀ", notStarted: "ਸ਼ੁਰੂ ਨਹੀਂ", loading: "ਅਗਲਾ ਕਦਮ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ…", offline: "ਮੁੜ ਜੁੜਦੇ ਸਮੇਂ ਝਲਕ ਦਿਖਾਈ ਜਾ ਰਹੀ ਹੈ।" },
};
