export type LifeStepHomeContent = {
  title: string;
  seoTitle: string;
  seoDescription: string;
  intro: string;
  getStarted: string;
  explore: string;
  themeLabel: string;
  featuresKicker: string;
  faqNav: string;
  privacyNav: string;
  termsNav: string;
  launchApp: string;
  footer: string;
  metrics: Array<{ value: string; label: string }>;
  features: Array<{ eyebrow: string; title: string; body: string; tags: string[]; accent: string }>;
  faq: Array<{ question: string; answer: string }>;
};

export type LifeStepHomePreview = {
  journey: string;
  steps: [string, string, string];
  current: string;
  conversation: string;
  practiceMode: string;
  nextStep: string;
  phrase: string;
  translation: string;
  playPhrase: string;
};

export type LifeStepAppCopy = {
  back: string; about: string; settings: string; messages: string; journey: string;
  explore: string; start: string; resume: string; restart: string; progress: string;
  completed: string; inProgress: string; notStarted: string; loading: string; offline: string;
};

const features = (values: Array<[string, string, string, string[]]>) => values.map(([eyebrow, title, body, tags], index) => ({
  eyebrow, title, body, tags, accent: ["red", "blue", "lime", "orange", "red", "blue"][index],
}));

export const lifeStepHome = {
  en: {
    title: "LifeStep - Practice Real-Life English", seoTitle: "LifeStep - Practice Real-Life English", seoDescription: "Interactive English conversations that prepare Canadian newcomers for real-life situations.",
    intro: "Build confidence for everyday life in Canada through guided English conversations based on situations newcomers actually face.", getStarted: "Take your first step", explore: "Explore product features", themeLabel: "Theme", featuresKicker: "Product features", faqNav: "FAQ", privacyNav: "Privacy Policy", termsNav: "Terms of Use", launchApp: "Open LifeStep", footer: "Real-life English for your new life in Canada.",
    metrics: [{ value: "10", label: "Languages" }, { value: "12", label: "Life stages" }, { value: "90+", label: "Real-life scenarios" }, { value: "4", label: "Learning steps" }],
    features: features([["01 / Journey", "Follow real life, step by step", "A visual journey turns important newcomer moments into a clear path you can explore at your pace.", ["Study", "Work", "Family"]], ["02 / Learn", "Know what to expect", "Build context and vocabulary before a real conversation begins.", ["Knowledge", "Vocabulary"]], ["03 / Conversation", "Listen, repeat, and respond", "Hear natural voices and practise a complete dialogue or move through it one line at a time.", ["Natural voices", "Bilingual dialogue"]], ["04 / Review", "Make the language yours", "Review key phrases, check your confidence, and complete each real-life scenario.", ["Key phrases", "Progress"]], ["05 / Personal", "A path shaped around you", "Choose study, work, or family and focus on the situations most useful to your life.", ["Your pace", "Your journey"]], ["06 / Push", "Keep your next step close", "Optional notifications and a message center help you return to the right moment.", ["Web Push", "Message center"]]]),
    faq: [{ question: "Who is LifeStep for?", answer: "LifeStep is designed for newcomers preparing for everyday life, study, work, and family situations in Canada." }, { question: "Can I change the language and theme?", answer: "Yes. LifeStep supports ten interface languages plus light, dark, and system themes." }, { question: "How does conversation practice work?", answer: "Read the complete bilingual dialogue or practise one line at a time with natural synthesized voices." }, { question: "What situations can I practise?", answer: "Explore arrival, housing, transportation, healthcare, banking, education, work, and community scenarios." }, { question: "Can I continue where I left off?", answer: "Yes. LifeStep records your scenario progress so you can return to the next step." }, { question: "Can I use LifeStep on my phone?", answer: "Yes. The responsive web app works on desktop and mobile and can be added to your home screen." }],
  },
  fr: {
    title: "LifeStep - Pratiquez l’anglais de la vie réelle", seoTitle: "LifeStep - Pratiquez l’anglais de la vie réelle", seoDescription: "Des conversations interactives en anglais pour préparer les nouveaux arrivants à la vie au Canada.", intro: "Gagnez en confiance pour la vie quotidienne au Canada grâce à des conversations guidées inspirées des situations réellement vécues par les nouveaux arrivants.", getStarted: "Faites le premier pas", explore: "Découvrir les fonctionnalités", themeLabel: "Thème", featuresKicker: "Fonctionnalités", faqNav: "FAQ", privacyNav: "Politique de confidentialité", termsNav: "Conditions d’utilisation", launchApp: "Ouvrir LifeStep", footer: "L’anglais de la vie réelle pour votre nouvelle vie au Canada.",
    metrics: [{ value: "10", label: "Langues" }, { value: "12", label: "Étapes de vie" }, { value: "90+", label: "Situations réelles" }, { value: "4", label: "Étapes d’apprentissage" }],
    features: features([["01 / Parcours", "Suivez la vraie vie, pas à pas", "Un parcours visuel transforme les moments importants en un chemin clair.", ["Études", "Travail", "Famille"]], ["02 / Apprendre", "Sachez à quoi vous attendre", "Découvrez le contexte et le vocabulaire avant la conversation.", ["Connaissances", "Vocabulaire"]], ["03 / Conversation", "Écoutez, répétez, répondez", "Écoutez des voix naturelles et pratiquez le dialogue complet ou phrase par phrase.", ["Voix naturelles", "Dialogue bilingue"]], ["04 / Révision", "Appropriez-vous la langue", "Révisez les phrases clés et terminez chaque scénario.", ["Phrases clés", "Progression"]], ["05 / Personnel", "Un parcours fait pour vous", "Choisissez études, travail ou famille.", ["Votre rythme", "Votre parcours"]], ["06 / Notifications", "Gardez la prochaine étape à portée", "Les notifications facultatives vous ramènent au bon moment.", ["Web Push", "Messages"]]]),
    faq: [{ question: "À qui s’adresse LifeStep ?", answer: "Aux nouveaux arrivants qui se préparent à la vie quotidienne, aux études, au travail et à la famille au Canada." }, { question: "Puis-je changer la langue et le thème ?", answer: "Oui. LifeStep prend en charge dix langues ainsi que les thèmes clair, sombre et système." }, { question: "Comment fonctionne la pratique ?", answer: "Lisez le dialogue bilingue ou avancez phrase par phrase avec des voix naturelles." }, { question: "Quelles situations puis-je pratiquer ?", answer: "L’arrivée, le logement, les transports, la santé, la banque, les études, le travail et la communauté." }, { question: "Puis-je reprendre ma progression ?", answer: "Oui. LifeStep enregistre votre progression pour reprendre à la prochaine étape." }, { question: "Puis-je utiliser LifeStep sur mobile ?", answer: "Oui. L’application web s’adapte au mobile et peut être ajoutée à l’écran d’accueil." }],
  },
  "zh-Hans": {
    title: "LifeStep - 练习真实生活英语", seoTitle: "LifeStep - 练习真实生活英语", seoDescription: "通过互动英语对话，帮助加拿大新移民为真实生活场景做好准备。", intro: "从初到加拿大的第一天，到安顿生活、求学就业与融入社区，通过真实场景对话，自信说出真正用得上的英语。", getStarted: "迈出第一步", explore: "了解产品功能", themeLabel: "主题", featuresKicker: "产品功能", faqNav: "常见问题", privacyNav: "隐私政策", termsNav: "使用条款", launchApp: "打开应用", footer: "为你的加拿大新生活练习真实英语。",
    metrics: [{ value: "10", label: "界面语言" }, { value: "12", label: "人生阶段" }, { value: "90+", label: "生活场景" }, { value: "4", label: "学习步骤" }],
    features: features([["01 / 旅程", "跟随真实生活，一步一步前进", "游戏地图把新移民的重要时刻整理成清晰、可探索的路径。", ["学习", "工作", "家庭"]], ["02 / 学习", "提前知道会发生什么", "在真实对话开始前掌握背景知识和实用词汇。", ["知识", "词汇"]], ["03 / 对话", "听、跟读、再回应", "使用自然语音练习完整对话，或逐句播放和练习。", ["自然语音", "双语对话"]], ["04 / 复习", "把英语真正变成自己的", "复习关键句、确认掌握程度并完成每个场景。", ["关键句", "学习进度"]], ["05 / 个性化", "围绕你的生活规划路径", "选择学习、工作或家庭，优先练习对你最有用的场景。", ["你的节奏", "你的旅程"]], ["06 / 通知", "不错过下一步", "可选通知和消息中心帮助你随时回到当前进度。", ["Web Push", "消息中心"]]]),
    faq: [{ question: "LifeStep 适合谁？", answer: "适合正在准备加拿大日常生活、学习、工作和家庭场景的新移民。" }, { question: "可以更换语言和主题吗？", answer: "可以。LifeStep 支持十种界面语言，以及浅色、深色和跟随系统主题。" }, { question: "对话练习如何使用？", answer: "你可以查看完整双语对话，也可以使用自然合成语音逐句练习。" }, { question: "可以练习哪些生活场景？", answer: "涵盖入境、住房、交通、医疗、银行、教育、求职以及社区生活等常见场景。" }, { question: "可以接着上次的进度学习吗？", answer: "可以。LifeStep 会记录场景进度，下次可以从当前步骤继续。" }, { question: "可以在手机上使用吗？", answer: "可以。页面适配桌面端和移动端，也可以添加到手机主屏幕。" }],
  },
  "zh-Hant": {
    title: "LifeStep - 練習真實生活英語", seoTitle: "LifeStep - 練習真實生活英語", seoDescription: "透過互動英語對話，幫助加拿大新移民為真實生活場景做好準備。", intro: "從初到加拿大的第一天，到安頓生活、求學就業與融入社區，透過真實場景對話，自信說出真正用得上的英語。", getStarted: "踏出第一步", explore: "了解產品功能", themeLabel: "主題", featuresKicker: "產品功能", faqNav: "常見問題", privacyNav: "隱私政策", termsNav: "使用條款", launchApp: "開啟應用", footer: "為你的加拿大新生活練習真實英語。",
    metrics: [{ value: "10", label: "介面語言" }, { value: "12", label: "人生階段" }, { value: "90+", label: "生活場景" }, { value: "4", label: "學習步驟" }],
    features: features([["01 / 旅程", "跟隨真實生活，一步一步前進", "遊戲地圖把新移民的重要時刻整理成清晰路徑。", ["學習", "工作", "家庭"]], ["02 / 學習", "提前知道會發生什麼", "在真實對話開始前掌握背景知識和實用詞彙。", ["知識", "詞彙"]], ["03 / 對話", "聽、跟讀、再回應", "使用自然語音練習完整對話，或逐句播放。", ["自然語音", "雙語對話"]], ["04 / 複習", "把英語真正變成自己的", "複習關鍵句並完成每個場景。", ["關鍵句", "學習進度"]], ["05 / 個人化", "圍繞你的生活規劃路徑", "選擇學習、工作或家庭。", ["你的節奏", "你的旅程"]], ["06 / 通知", "不錯過下一步", "可選通知和訊息中心幫助你回到進度。", ["Web Push", "訊息中心"]]]),
    faq: [{ question: "LifeStep 適合誰？", answer: "適合正在準備加拿大日常生活、學習、工作和家庭場景的新移民。" }, { question: "可以更換語言和主題嗎？", answer: "可以。LifeStep 支援十種介面語言及淺色、深色和系統主題。" }, { question: "對話練習如何使用？", answer: "查看完整雙語對話，或使用自然合成語音逐句練習。" }, { question: "可以練習哪些生活場景？", answer: "涵蓋入境、住房、交通、醫療、銀行、教育、求職與社區生活。" }, { question: "可以接續上次進度嗎？", answer: "可以。LifeStep 會記錄場景進度，下次從目前步驟繼續。" }, { question: "可以在手機上使用嗎？", answer: "可以。頁面支援桌面與行動裝置，也能加入手機主畫面。" }],
  },
  es: {
    title: "LifeStep - Practica inglés para la vida real", seoTitle: "LifeStep - Practica inglés para la vida real", seoDescription: "Conversaciones interactivas en inglés para preparar a los recién llegados a la vida en Canadá.", intro: "Gana confianza para la vida diaria en Canadá con conversaciones guiadas basadas en situaciones reales de los recién llegados.", getStarted: "Da tu primer paso", explore: "Explorar funciones", themeLabel: "Tema", featuresKicker: "Funciones del producto", faqNav: "Preguntas", privacyNav: "Privacidad", termsNav: "Condiciones", launchApp: "Abrir LifeStep", footer: "Inglés para la vida real en tu nueva vida en Canadá.",
    metrics: [{ value: "10", label: "Idiomas" }, { value: "12", label: "Etapas de vida" }, { value: "90+", label: "Situaciones reales" }, { value: "4", label: "Pasos de aprendizaje" }],
    features: features([["01 / Recorrido", "Sigue la vida real, paso a paso", "Un mapa visual convierte momentos importantes en un camino claro.", ["Estudio", "Trabajo", "Familia"]], ["02 / Aprende", "Sabe qué esperar", "Aprende el contexto y el vocabulario antes de conversar.", ["Conocimiento", "Vocabulario"]], ["03 / Conversación", "Escucha, repite y responde", "Practica diálogos completos o frase por frase con voces naturales.", ["Voces naturales", "Diálogo bilingüe"]], ["04 / Repaso", "Haz tuyo el idioma", "Repasa frases clave y completa cada escenario.", ["Frases clave", "Progreso"]], ["05 / Personal", "Un camino hecho para ti", "Elige estudio, trabajo o familia.", ["Tu ritmo", "Tu recorrido"]], ["06 / Avisos", "Mantén cerca el siguiente paso", "Las notificaciones opcionales te ayudan a continuar.", ["Web Push", "Mensajes"]]]),
    faq: [{ question: "¿Para quién es LifeStep?", answer: "Para recién llegados que se preparan para la vida diaria, el estudio, el trabajo y la familia en Canadá." }, { question: "¿Puedo cambiar idioma y tema?", answer: "Sí. LifeStep ofrece diez idiomas y temas claro, oscuro y del sistema." }, { question: "¿Cómo se practica la conversación?", answer: "Lee el diálogo bilingüe completo o practica frase por frase con voces naturales." }, { question: "¿Qué situaciones puedo practicar?", answer: "Llegada, vivienda, transporte, salud, banca, educación, trabajo y comunidad." }, { question: "¿Puedo continuar mi progreso?", answer: "Sí. LifeStep guarda el progreso para que continúes desde el siguiente paso." }, { question: "¿Funciona en el móvil?", answer: "Sí. La aplicación se adapta al móvil y puede añadirse a la pantalla de inicio." }],
  },
  ja: {
    title: "LifeStep - 実生活の英語を練習", seoTitle: "LifeStep - 実生活の英語を練習", seoDescription: "カナダでの実生活に備えるためのインタラクティブな英会話練習。", intro: "新しくカナダで暮らす人が実際に出会う場面に沿った会話で、日常生活に必要な英語と自信を身につけます。", getStarted: "最初の一歩", explore: "機能を見る", themeLabel: "テーマ", featuresKicker: "製品機能", faqNav: "よくある質問", privacyNav: "プライバシー", termsNav: "利用規約", launchApp: "LifeStep を開く", footer: "カナダでの新生活に役立つ実践英語。",
    metrics: [{ value: "10", label: "言語" }, { value: "12", label: "ライフステージ" }, { value: "90+", label: "生活シーン" }, { value: "4", label: "学習ステップ" }],
    features: features([["01 / 旅", "実生活を一歩ずつ", "新生活の大切な場面を見やすいマップで進みます。", ["留学", "仕事", "家族"]], ["02 / 学ぶ", "場面を先に理解", "会話の前に背景と語彙を学びます。", ["知識", "語彙"]], ["03 / 会話", "聞いて、繰り返して、答える", "自然な音声で会話全体または一文ずつ練習します。", ["自然な音声", "二言語会話"]], ["04 / 復習", "英語を自分のものに", "重要表現を復習して場面を完了します。", ["重要表現", "進捗"]], ["05 / 個別", "あなたに合う道", "留学、仕事、家族から選べます。", ["自分のペース", "自分の旅"]], ["06 / 通知", "次の一歩を忘れない", "通知とメッセージで学習に戻れます。", ["Web Push", "メッセージ"]]]),
    faq: [{ question: "LifeStep は誰向けですか？", answer: "カナダでの日常、留学、仕事、家族生活に備える新移民向けです。" }, { question: "言語とテーマは変更できますか？", answer: "はい。10言語とライト、ダーク、システムテーマに対応します。" }, { question: "会話練習はどう進めますか？", answer: "二言語の会話全体、または自然な合成音声で一文ずつ練習できます。" }, { question: "どんな場面を練習できますか？", answer: "入国、住居、交通、医療、銀行、教育、仕事、地域生活を練習できます。" }, { question: "前回の続きから学べますか？", answer: "はい。進捗が保存され、次のステップから再開できます。" }, { question: "スマートフォンでも使えますか？", answer: "はい。モバイル対応で、ホーム画面にも追加できます。" }],
  },
  ko: {
    title: "LifeStep - 실생활 영어 연습", seoTitle: "LifeStep - 실생활 영어 연습", seoDescription: "캐나다 새 이민자의 실생활을 준비하는 대화형 영어 회화 연습.", intro: "새 이민자가 실제로 마주하는 상황을 바탕으로 한 영어 대화로 캐나다 일상에 필요한 자신감을 키우세요.", getStarted: "첫걸음 시작", explore: "제품 기능 보기", themeLabel: "테마", featuresKicker: "제품 기능", faqNav: "자주 묻는 질문", privacyNav: "개인정보", termsNav: "이용약관", launchApp: "LifeStep 열기", footer: "캐나다의 새로운 삶을 위한 실생활 영어.",
    metrics: [{ value: "10", label: "언어" }, { value: "12", label: "생활 단계" }, { value: "90+", label: "생활 상황" }, { value: "4", label: "학습 단계" }],
    features: features([["01 / 여정", "실생활을 한 걸음씩", "중요한 새 이민자 경험을 명확한 지도에서 탐색합니다.", ["학업", "직장", "가족"]], ["02 / 학습", "상황을 미리 이해하세요", "대화 전에 배경과 어휘를 익힙니다.", ["지식", "어휘"]], ["03 / 대화", "듣고, 따라 하고, 응답하세요", "자연스러운 음성으로 전체 대화 또는 한 문장씩 연습합니다.", ["자연스러운 음성", "이중 언어"]], ["04 / 복습", "영어를 내 것으로", "핵심 문장을 복습하고 상황을 완료합니다.", ["핵심 문장", "진행률"]], ["05 / 맞춤", "나에게 맞는 경로", "학업, 직장 또는 가족을 선택합니다.", ["나의 속도", "나의 여정"]], ["06 / 알림", "다음 단계를 가까이", "선택 알림으로 학습을 이어갑니다.", ["Web Push", "메시지"]]]),
    faq: [{ question: "LifeStep은 누구를 위한 앱인가요?", answer: "캐나다 일상, 학업, 직장, 가족생활을 준비하는 새 이민자를 위한 앱입니다." }, { question: "언어와 테마를 바꿀 수 있나요?", answer: "네. 10개 언어와 라이트, 다크, 시스템 테마를 지원합니다." }, { question: "대화 연습은 어떻게 하나요?", answer: "이중 언어 대화 전체 또는 자연스러운 합성 음성으로 한 문장씩 연습합니다." }, { question: "어떤 상황을 연습할 수 있나요?", answer: "입국, 주거, 교통, 의료, 은행, 교육, 취업, 지역생활을 연습할 수 있습니다." }, { question: "이전 진도를 이어갈 수 있나요?", answer: "네. 진행 상황이 저장되어 다음 단계부터 이어갈 수 있습니다." }, { question: "휴대폰에서도 사용할 수 있나요?", answer: "네. 모바일에 맞게 표시되며 홈 화면에 추가할 수 있습니다." }],
  },
  ru: {
    title: "LifeStep — английский для реальной жизни", seoTitle: "LifeStep — английский для реальной жизни", seoDescription: "Интерактивные диалоги для подготовки новых жителей к жизни в Канаде.", intro: "Развивайте уверенность для повседневной жизни в Канаде с диалогами, основанными на реальных ситуациях новых жителей.", getStarted: "Сделать первый шаг", explore: "Посмотреть функции", themeLabel: "Тема", featuresKicker: "Возможности продукта", faqNav: "Вопросы", privacyNav: "Конфиденциальность", termsNav: "Условия", launchApp: "Открыть LifeStep", footer: "Практический английский для новой жизни в Канаде.",
    metrics: [{ value: "10", label: "Языков" }, { value: "12", label: "Этапов жизни" }, { value: "90+", label: "Жизненных ситуаций" }, { value: "4", label: "Шага обучения" }],
    features: features([["01 / Путь", "Реальная жизнь шаг за шагом", "Наглядная карта превращает важные ситуации в понятный путь.", ["Учёба", "Работа", "Семья"]], ["02 / Учёба", "Знайте, чего ожидать", "Изучите контекст и слова до начала разговора.", ["Знания", "Словарь"]], ["03 / Диалог", "Слушайте, повторяйте, отвечайте", "Практикуйте весь диалог или по одной фразе с естественными голосами.", ["Естественные голоса", "Два языка"]], ["04 / Повторение", "Сделайте язык своим", "Повторите ключевые фразы и завершите сценарий.", ["Ключевые фразы", "Прогресс"]], ["05 / Личное", "Путь для вас", "Выберите учёбу, работу или семью.", ["Ваш темп", "Ваш путь"]], ["06 / Уведомления", "Следующий шаг рядом", "Необязательные уведомления помогают продолжить.", ["Web Push", "Сообщения"]]]),
    faq: [{ question: "Для кого LifeStep?", answer: "Для новых жителей, готовящихся к повседневной жизни, учёбе, работе и семье в Канаде." }, { question: "Можно сменить язык и тему?", answer: "Да. Доступны десять языков и светлая, тёмная и системная темы." }, { question: "Как проходит практика диалога?", answer: "Читайте весь двуязычный диалог или практикуйте по фразе с естественными голосами." }, { question: "Какие ситуации можно практиковать?", answer: "Приезд, жильё, транспорт, медицина, банк, образование, работа и жизнь в сообществе." }, { question: "Можно продолжить с прошлого места?", answer: "Да. LifeStep сохраняет прогресс и позволяет вернуться к следующему шагу." }, { question: "Работает ли LifeStep на телефоне?", answer: "Да. Приложение адаптировано для мобильных устройств и добавляется на главный экран." }],
  },
  vi: {
    title: "LifeStep - Luyện tiếng Anh đời thực", seoTitle: "LifeStep - Luyện tiếng Anh đời thực", seoDescription: "Hội thoại tiếng Anh tương tác giúp người mới đến chuẩn bị cho cuộc sống tại Canada.", intro: "Tự tin hơn trong cuộc sống hằng ngày tại Canada qua các hội thoại có hướng dẫn dựa trên tình huống thực tế của người mới đến.", getStarted: "Bước đầu tiên", explore: "Khám phá tính năng", themeLabel: "Giao diện", featuresKicker: "Tính năng sản phẩm", faqNav: "Câu hỏi", privacyNav: "Quyền riêng tư", termsNav: "Điều khoản", launchApp: "Mở LifeStep", footer: "Tiếng Anh đời thực cho cuộc sống mới tại Canada.",
    metrics: [{ value: "10", label: "Ngôn ngữ" }, { value: "12", label: "Giai đoạn cuộc sống" }, { value: "90+", label: "Tình huống thực tế" }, { value: "4", label: "Bước học" }],
    features: features([["01 / Hành trình", "Theo đời thực, từng bước", "Bản đồ trực quan biến các tình huống quan trọng thành lộ trình rõ ràng.", ["Học tập", "Công việc", "Gia đình"]], ["02 / Học", "Biết trước điều sẽ xảy ra", "Học bối cảnh và từ vựng trước khi hội thoại.", ["Kiến thức", "Từ vựng"]], ["03 / Hội thoại", "Nghe, lặp lại và trả lời", "Luyện cả đoạn hoặc từng câu với giọng đọc tự nhiên.", ["Giọng tự nhiên", "Song ngữ"]], ["04 / Ôn tập", "Biến ngôn ngữ thành của bạn", "Ôn cụm từ chính và hoàn thành tình huống.", ["Cụm từ", "Tiến độ"]], ["05 / Cá nhân", "Lộ trình dành cho bạn", "Chọn học tập, công việc hoặc gia đình.", ["Nhịp của bạn", "Hành trình của bạn"]], ["06 / Thông báo", "Giữ bước tiếp theo bên mình", "Thông báo tùy chọn giúp bạn tiếp tục.", ["Web Push", "Tin nhắn"]]]),
    faq: [{ question: "LifeStep dành cho ai?", answer: "Dành cho người mới đến chuẩn bị cho đời sống, học tập, công việc và gia đình tại Canada." }, { question: "Có thể đổi ngôn ngữ và giao diện không?", answer: "Có. LifeStep hỗ trợ mười ngôn ngữ và giao diện sáng, tối hoặc theo hệ thống." }, { question: "Luyện hội thoại như thế nào?", answer: "Đọc toàn bộ hội thoại song ngữ hoặc luyện từng câu với giọng tổng hợp tự nhiên." }, { question: "Có thể luyện những tình huống nào?", answer: "Nhập cảnh, nhà ở, giao thông, y tế, ngân hàng, giáo dục, việc làm và cộng đồng." }, { question: "Có thể tiếp tục tiến độ cũ không?", answer: "Có. LifeStep lưu tiến độ để bạn tiếp tục từ bước tiếp theo." }, { question: "Có dùng được trên điện thoại không?", answer: "Có. Ứng dụng thích ứng với di động và có thể thêm vào màn hình chính." }],
  },
  pa: {
    title: "LifeStep - ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀ ਅੰਗਰੇਜ਼ੀ ਦਾ ਅਭਿਆਸ", seoTitle: "LifeStep - ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀ ਅੰਗਰੇਜ਼ੀ ਦਾ ਅਭਿਆਸ", seoDescription: "ਕੈਨੇਡਾ ਵਿੱਚ ਨਵੀਂ ਜ਼ਿੰਦਗੀ ਲਈ ਇੰਟਰਐਕਟਿਵ ਅੰਗਰੇਜ਼ੀ ਗੱਲਬਾਤ।", intro: "ਨਵੇਂ ਆਉਣ ਵਾਲਿਆਂ ਦੀਆਂ ਅਸਲ ਸਥਿਤੀਆਂ ਉੱਤੇ ਆਧਾਰਿਤ ਗੱਲਬਾਤਾਂ ਨਾਲ ਕੈਨੇਡਾ ਦੀ ਰੋਜ਼ਾਨਾ ਜ਼ਿੰਦਗੀ ਲਈ ਭਰੋਸਾ ਬਣਾਓ।", getStarted: "ਪਹਿਲਾ ਕਦਮ ਚੁੱਕੋ", explore: "ਫੀਚਰ ਵੇਖੋ", themeLabel: "ਥੀਮ", featuresKicker: "ਉਤਪਾਦ ਫੀਚਰ", faqNav: "ਸਵਾਲ", privacyNav: "ਪਰਦੇਦਾਰੀ", termsNav: "ਸ਼ਰਤਾਂ", launchApp: "LifeStep ਖੋਲ੍ਹੋ", footer: "ਕੈਨੇਡਾ ਵਿੱਚ ਨਵੀਂ ਜ਼ਿੰਦਗੀ ਲਈ ਅਸਲ ਅੰਗਰੇਜ਼ੀ।",
    metrics: [{ value: "10", label: "ਭਾਸ਼ਾਵਾਂ" }, { value: "12", label: "ਜੀਵਨ ਪੜਾਅ" }, { value: "90+", label: "ਅਸਲ ਸਥਿਤੀਆਂ" }, { value: "4", label: "ਸਿੱਖਣ ਦੇ ਕਦਮ" }],
    features: features([["01 / ਯਾਤਰਾ", "ਅਸਲ ਜ਼ਿੰਦਗੀ, ਕਦਮ ਦਰ ਕਦਮ", "ਇੱਕ ਵਿਜ਼ੂਅਲ ਨਕਸ਼ਾ ਮਹੱਤਵਪੂਰਨ ਪਲਾਂ ਨੂੰ ਸਾਫ਼ ਰਸਤੇ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।", ["ਪੜ੍ਹਾਈ", "ਕੰਮ", "ਪਰਿਵਾਰ"]], ["02 / ਸਿੱਖੋ", "ਪਹਿਲਾਂ ਜਾਣੋ ਕੀ ਹੋਵੇਗਾ", "ਗੱਲਬਾਤ ਤੋਂ ਪਹਿਲਾਂ ਸੰਦਰਭ ਅਤੇ ਸ਼ਬਦਾਵਲੀ ਸਿੱਖੋ।", ["ਗਿਆਨ", "ਸ਼ਬਦਾਵਲੀ"]], ["03 / ਗੱਲਬਾਤ", "ਸੁਣੋ, ਦੁਹਰਾਓ, ਜਵਾਬ ਦਿਓ", "ਕੁਦਰਤੀ ਆਵਾਜ਼ਾਂ ਨਾਲ ਪੂਰੀ ਜਾਂ ਲਾਈਨ-ਦਰ-ਲਾਈਨ ਗੱਲਬਾਤ ਕਰੋ।", ["ਕੁਦਰਤੀ ਆਵਾਜ਼", "ਦੋ ਭਾਸ਼ਾਵਾਂ"]], ["04 / ਸਮੀਖਿਆ", "ਭਾਸ਼ਾ ਨੂੰ ਆਪਣਾ ਬਣਾਓ", "ਮੁੱਖ ਵਾਕਾਂਸ਼ ਦੁਹਰਾਓ ਅਤੇ ਦ੍ਰਿਸ਼ ਪੂਰਾ ਕਰੋ।", ["ਮੁੱਖ ਵਾਕ", "ਤਰੱਕੀ"]], ["05 / ਨਿੱਜੀ", "ਤੁਹਾਡੇ ਲਈ ਰਸਤਾ", "ਪੜ੍ਹਾਈ, ਕੰਮ ਜਾਂ ਪਰਿਵਾਰ ਚੁਣੋ।", ["ਤੁਹਾਡੀ ਰਫ਼ਤਾਰ", "ਤੁਹਾਡੀ ਯਾਤਰਾ"]], ["06 / ਸੂਚਨਾ", "ਅਗਲਾ ਕਦਮ ਨੇੜੇ ਰੱਖੋ", "ਚੋਣਵੀਂ ਸੂਚਨਾਵਾਂ ਅਭਿਆਸ ਜਾਰੀ ਰੱਖਦੀਆਂ ਹਨ।", ["Web Push", "ਸੁਨੇਹੇ"]]]),
    faq: [{ question: "LifeStep ਕਿਸ ਲਈ ਹੈ?", answer: "ਕੈਨੇਡਾ ਵਿੱਚ ਰੋਜ਼ਾਨਾ ਜੀਵਨ, ਪੜ੍ਹਾਈ, ਕੰਮ ਅਤੇ ਪਰਿਵਾਰ ਲਈ ਤਿਆਰ ਹੋ ਰਹੇ ਨਵੇਂ ਲੋਕਾਂ ਲਈ।" }, { question: "ਕੀ ਭਾਸ਼ਾ ਅਤੇ ਥੀਮ ਬਦਲ ਸਕਦੇ ਹਾਂ?", answer: "ਹਾਂ। ਦਸ ਭਾਸ਼ਾਵਾਂ ਅਤੇ ਲਾਈਟ, ਡਾਰਕ ਜਾਂ ਸਿਸਟਮ ਥੀਮ ਉਪਲਬਧ ਹਨ।" }, { question: "ਗੱਲਬਾਤ ਦਾ ਅਭਿਆਸ ਕਿਵੇਂ ਹੁੰਦਾ ਹੈ?", answer: "ਦੋ-ਭਾਸ਼ਾਈ ਗੱਲਬਾਤ ਪੜ੍ਹੋ ਜਾਂ ਕੁਦਰਤੀ ਆਵਾਜ਼ ਨਾਲ ਇੱਕ-ਇੱਕ ਲਾਈਨ ਦਾ ਅਭਿਆਸ ਕਰੋ।" }, { question: "ਕਿਹੜੀਆਂ ਸਥਿਤੀਆਂ ਦਾ ਅਭਿਆਸ ਕਰ ਸਕਦਾ ਹਾਂ?", answer: "ਪਹੁੰਚ, ਘਰ, ਆਵਾਜਾਈ, ਸਿਹਤ, ਬੈਂਕ, ਸਿੱਖਿਆ, ਕੰਮ ਅਤੇ ਕਮਿਊਨਿਟੀ।" }, { question: "ਕੀ ਪਿਛਲੀ ਤਰੱਕੀ ਤੋਂ ਜਾਰੀ ਰੱਖ ਸਕਦਾ ਹਾਂ?", answer: "ਹਾਂ। LifeStep ਤਰੱਕੀ ਸੰਭਾਲਦਾ ਹੈ ਤਾਂ ਜੋ ਤੁਸੀਂ ਅਗਲੇ ਕਦਮ ਤੋਂ ਜਾਰੀ ਰੱਖੋ।" }, { question: "ਕੀ ਇਹ ਫੋਨ ਉੱਤੇ ਚੱਲਦਾ ਹੈ?", answer: "ਹਾਂ। ਇਹ ਮੋਬਾਈਲ ਲਈ ਅਨੁਕੂਲ ਹੈ ਅਤੇ ਹੋਮ ਸਕ੍ਰੀਨ ਉੱਤੇ ਜੋੜਿਆ ਜਾ ਸਕਦਾ ਹੈ।" }],
  },
} satisfies Record<string, LifeStepHomeContent>;

export const lifeStepHomePreview: Record<string, LifeStepHomePreview> = {
  en: { journey: "Journey", steps: ["Arrive", "Find a home", "Finances"], current: "You are here", conversation: "Conversation", practiceMode: "Practice mode", nextStep: "Next step ready", phrase: "Could you repeat that?", translation: "Ask the other person to say it again.", playPhrase: "Play phrase" },
  fr: { journey: "Parcours", steps: ["Arrivée", "Trouver un logement", "Finances"], current: "Vous êtes ici", conversation: "Conversation", practiceMode: "Mode pratique", nextStep: "Prochaine étape prête", phrase: "Could you repeat that?", translation: "Pourriez-vous répéter ?", playPhrase: "Écouter la phrase" },
  "zh-Hans": { journey: "旅程", steps: ["抵达加拿大", "寻找住房", "办理财务"], current: "你在这里", conversation: "对话练习", practiceMode: "练习模式", nextStep: "下一步已准备", phrase: "Could you repeat that?", translation: "可以请您再说一遍吗？", playPhrase: "播放句子" },
  "zh-Hant": { journey: "旅程", steps: ["抵達加拿大", "尋找住房", "辦理財務"], current: "你在這裡", conversation: "對話練習", practiceMode: "練習模式", nextStep: "下一步已準備", phrase: "Could you repeat that?", translation: "可以請您再說一遍嗎？", playPhrase: "播放句子" },
  es: { journey: "Recorrido", steps: ["Llegada", "Encontrar vivienda", "Finanzas"], current: "Estás aquí", conversation: "Conversación", practiceMode: "Modo práctica", nextStep: "Siguiente paso listo", phrase: "Could you repeat that?", translation: "¿Podría repetirlo?", playPhrase: "Reproducir frase" },
  ja: { journey: "旅", steps: ["到着", "住まい探し", "お金の手続き"], current: "現在地", conversation: "会話", practiceMode: "練習モード", nextStep: "次のステップ", phrase: "Could you repeat that?", translation: "もう一度言っていただけますか？", playPhrase: "フレーズを再生" },
  ko: { journey: "여정", steps: ["도착", "집 찾기", "금융 업무"], current: "현재 위치", conversation: "대화", practiceMode: "연습 모드", nextStep: "다음 단계 준비됨", phrase: "Could you repeat that?", translation: "다시 말씀해 주시겠어요?", playPhrase: "문장 재생" },
  ru: { journey: "Путь", steps: ["Прибытие", "Поиск жилья", "Финансы"], current: "Вы здесь", conversation: "Диалог", practiceMode: "Режим практики", nextStep: "Следующий шаг готов", phrase: "Could you repeat that?", translation: "Не могли бы вы повторить?", playPhrase: "Прослушать фразу" },
  vi: { journey: "Hành trình", steps: ["Đến Canada", "Tìm nhà", "Tài chính"], current: "Bạn đang ở đây", conversation: "Hội thoại", practiceMode: "Chế độ luyện tập", nextStep: "Bước tiếp theo đã sẵn sàng", phrase: "Could you repeat that?", translation: "Bạn có thể nhắc lại không?", playPhrase: "Phát câu" },
  pa: { journey: "ਯਾਤਰਾ", steps: ["ਪਹੁੰਚ", "ਘਰ ਲੱਭੋ", "ਵਿੱਤ"], current: "ਤੁਸੀਂ ਇੱਥੇ ਹੋ", conversation: "ਗੱਲਬਾਤ", practiceMode: "ਅਭਿਆਸ ਮੋਡ", nextStep: "ਅਗਲਾ ਕਦਮ ਤਿਆਰ", phrase: "Could you repeat that?", translation: "ਕੀ ਤੁਸੀਂ ਇਹ ਦੁਬਾਰਾ ਕਹਿ ਸਕਦੇ ਹੋ?", playPhrase: "ਵਾਕ ਚਲਾਓ" },
};

export const lifeStepAppCopy: Record<string, LifeStepAppCopy> = {
  en: { back: "Back", about: "About", settings: "Settings", messages: "Messages", journey: "Your journey", explore: "Explore", start: "Start exploring", resume: "Continue exploring", restart: "Explore again", progress: "Progress", completed: "Completed", inProgress: "In progress", notStarted: "Not started", loading: "Preparing your next step…", offline: "Showing a practice preview while the service reconnects." },
  fr: { back: "Retour", about: "À propos", settings: "Réglages", messages: "Messages", journey: "Votre parcours", explore: "Explorer", start: "Commencer", resume: "Continuer", restart: "Recommencer", progress: "Progression", completed: "Terminé", inProgress: "En cours", notStarted: "Pas commencé", loading: "Préparation de la prochaine étape…", offline: "Aperçu affiché pendant la reconnexion." },
  "zh-Hans": { back: "返回", about: "关于", settings: "设置", messages: "消息中心", journey: "你的旅程", explore: "探索", start: "开始探索", resume: "继续探索", restart: "重新探索", progress: "进度", completed: "已完成", inProgress: "进行中", notStarted: "未开始", loading: "正在准备下一步…", offline: "服务连接中，当前展示练习预览。" },
  "zh-Hant": { back: "返回", about: "關於", settings: "設定", messages: "訊息中心", journey: "你的旅程", explore: "探索", start: "開始探索", resume: "繼續探索", restart: "重新探索", progress: "進度", completed: "已完成", inProgress: "進行中", notStarted: "未開始", loading: "正在準備下一步…", offline: "服務連線中，目前顯示練習預覽。" },
  es: { back: "Atrás", about: "Acerca de", settings: "Ajustes", messages: "Mensajes", journey: "Tu recorrido", explore: "Explorar", start: "Empezar", resume: "Continuar", restart: "Explorar de nuevo", progress: "Progreso", completed: "Completado", inProgress: "En progreso", notStarted: "Sin empezar", loading: "Preparando tu próximo paso…", offline: "Mostrando una vista previa mientras se reconecta." },
  ja: { back: "戻る", about: "概要", settings: "設定", messages: "メッセージ", journey: "あなたの旅", explore: "探索", start: "探索を始める", resume: "探索を続ける", restart: "もう一度探索", progress: "進捗", completed: "完了", inProgress: "進行中", notStarted: "未開始", loading: "次のステップを準備中…", offline: "再接続中のためプレビューを表示しています。" },
  ko: { back: "뒤로", about: "정보", settings: "설정", messages: "메시지", journey: "나의 여정", explore: "탐색", start: "탐색 시작", resume: "계속 탐색", restart: "다시 탐색", progress: "진행률", completed: "완료", inProgress: "진행 중", notStarted: "시작 전", loading: "다음 단계를 준비 중…", offline: "다시 연결하는 동안 미리보기를 표시합니다." },
  ru: { back: "Назад", about: "О приложении", settings: "Настройки", messages: "Сообщения", journey: "Ваш путь", explore: "Изучить", start: "Начать", resume: "Продолжить", restart: "Начать заново", progress: "Прогресс", completed: "Завершено", inProgress: "В процессе", notStarted: "Не начато", loading: "Готовим следующий шаг…", offline: "Показан предварительный режим во время подключения." },
  vi: { back: "Quay lại", about: "Giới thiệu", settings: "Cài đặt", messages: "Tin nhắn", journey: "Hành trình", explore: "Khám phá", start: "Bắt đầu", resume: "Tiếp tục", restart: "Khám phá lại", progress: "Tiến độ", completed: "Đã hoàn thành", inProgress: "Đang thực hiện", notStarted: "Chưa bắt đầu", loading: "Đang chuẩn bị bước tiếp theo…", offline: "Hiển thị bản xem trước khi kết nối lại." },
  pa: { back: "ਵਾਪਸ", about: "ਜਾਣਕਾਰੀ", settings: "ਸੈਟਿੰਗਾਂ", messages: "ਸੁਨੇਹੇ", journey: "ਤੁਹਾਡੀ ਯਾਤਰਾ", explore: "ਖੋਜੋ", start: "ਸ਼ੁਰੂ ਕਰੋ", resume: "ਜਾਰੀ ਰੱਖੋ", restart: "ਮੁੜ ਸ਼ੁਰੂ", progress: "ਤਰੱਕੀ", completed: "ਪੂਰਾ", inProgress: "ਜਾਰੀ", notStarted: "ਸ਼ੁਰੂ ਨਹੀਂ", loading: "ਅਗਲਾ ਕਦਮ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ…", offline: "ਮੁੜ ਜੁੜਦੇ ਸਮੇਂ ਝਲਕ ਦਿਖਾਈ ਜਾ ਰਹੀ ਹੈ।" },
};
